### ISSUE TITLE
sql helper method doesn't work with json fields

### ISSUE THREAD

**Issue by iMoses** [porsager/postgres#114]
I get the following error when trying to insert a json field value using the sql helper.
```
Error: invalid input syntax for type json
    at Object.generic (/home/imoses/repositories/data-sync/node_modules/postgres/lib/types.js:200:5)
    at Object.ErrorResponse (/home/imoses/repositories/data-sync/node_modules/postgres/lib/backend.js:124:33)
    at Socket.data (/home/imoses/repositories/data-sync/node_modules/postgres/lib/connection.js:167:25)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```
The issues seems to be that the value is cast into a string using `toString` instead of `JSON.stringify` or another method that would allow for passing the object as is.
```
{
  sig: false,
  str: 'INSERT INTO identities (core_id,core_rev,last_sync,name,type,external_type,properties) values ($1,$2,$3,$4,$5,$6,$7),($8,$9,$10,$11,$12,$13,$14)',
  args: [
    {
      type: 0,
      value: '96d1bdaed5b60de16efc299173fa0e3b6789c2d8'
    },
    { type: 0, value: '_bEyqvMK---' },
    { type: 0, value: '2020-09-08T10:04:43.635566' },
    { type: 0, value: 'Category' },
    { type: 0, value: 'Group' },
    { type: 0, value: undefined },
    { type: 0, value: '[object Object]' },  // notice me! I'm a json value
    {
      type: 0,
      value: 'e2bea6a5a805ce73a3319186ed221152b1e5e7b7'
    },
    { type: 0, value: '_bHbUyUu---' },
    { type: 0, value: '2020-09-16 14:34:42.805604' },
    { type: 0, value: 'Affiliate Support' },
    { type: 0, value: 'Group' },
    { type: 0, value: undefined },
    { type: 0, value: '[object Object]' },  // notice me! I'm a json value
    dynamic: true
  ]
}
```
I'm still debugging, may update soon with more details..

**Comment by porsager** [comment]
You need to use `sql.json(jsonObjectHere)` to pass json as argument ;)

**Comment by iMoses** [comment]
I just got there myself :sweat_smile: thanks :)
Is it documented and i missed it? I didn't find anything while looking for a solution

**Comment by porsager** [comment]
Hehe, I don't know if it's too hidden, but it's here in the readme: https://github.com/porsager/postgres#json-sqljsonobject

**Comment by henryzhang03** [comment]
hello, @porsager , I read a lot of the github issues but not using sql.json does not work for multiple updates in 1 query where one of the fields in each update is a jsonb.
