### ISSUE TITLE
conditional Tokens (where, and, or, ...)

### ISSUE THREAD

**Issue by mortifia** [porsager/postgres#152]
there is a solution to add "and xxx.xxx = $ {xxx.xxx.xxx}" according to a condition?
to avoid having to maintain all the variants of the request.

example : 
```js
// if source.ticketUuid exist
sql`
    select t.*
      from chat.tickets t
      join chat.ticket_user tu 
        on t.ticket_uuid = tu.ticket_uuid
      where tu.user_uuid = ${this.context.user_uuid}
        and tu.ticket_uuid = ${source.ticketUuid}`;

// else
sql`
    select t.*
      from chat.tickets t
      join chat.ticket_user tu 
        on t.ticket_uuid = tu.ticket_uuid
      where tu.user_uuid = ${this.context.user_uuid}`;
```

**Comment by porsager** [comment]
Until dynamic queries lands you can do like this:

```js
sql`
    select t.*
      from chat.tickets t
      join chat.ticket_user tu 
        on t.ticket_uuid = tu.ticket_uuid
     where tu.user_uuid = ${this.context.user_uuid}
       and (tu.ticket_uuid = ${source.ticketUuid} or ${ source.ticketUuid || null } is null)`;
```

**Comment by mortifia** [comment]
```js

sql`
    select t.*
      from chat.tickets t
      join chat.ticket_user tu 
        on t.ticket_uuid = tu.ticket_uuid
      where tu.user_uuid = ${this.context.user_uuid}
        and (tu.ticket_uuid = ${check1} 
          or ${check1} is null)`
```

im get :


```json
{
  "errors": [
    {
      "message": "n'a pas pu déterminer le type de données du paramètre $3",
      "locations": [
        {
          "line": 12,
          "column": 3
        }
      ],
      "path": [
        "tickets"
      ],
      "extensions": {
        "code": "protectedError",
        "exception": {
          "name": "protectedError",
          "severity_local": "ERREUR",
          "severity": "ERROR",
          "code": "42P18",
          "file": "postgres.c",
          "line": "1496",
          "routine": "exec_parse_message",
          "stacktrace": [
            "PostgresError: could not determine the data type of parameter $ 3",
            "    at Object.ErrorResponse (/home/mortifia/Bureau/api/node_modules/postgres-data-source/postgres-patch/lib/backend.js:130:33)",
            "    at Socket.data (/home/mortifia/Bureau/api/node_modules/postgres-data-source/postgres-patch/lib/connection.js:233:25)",
            "    at Socket.emit (events.js:315:20)",
            "    at addChunk (internal/streams/readable.js:309:12)",
            "    at readableAddChunk (internal/streams/readable.js:284:9)",
            "    at Socket.Readable.push (internal/streams/readable.js:223:10)",
            "    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)",
            "    at cachedError (/home/mortifia/Bureau/api/node_modules/postgres-data-source/postgres-patch/lib/index.js:195:25)",
            "    at query (/home/mortifia/Bureau/api/node_modules/postgres-data-source/postgres-patch/lib/index.js:169:56)",
            "    at postgresDB.postgres (/home/mortifia/Bureau/api/node_modules/postgres-data-source/postgres-patch/lib/index.js:70:12)",
            "    at postgresDB.getTicketsByUserUuid (/home/mortifia/Bureau/api/postgresDatabase.js:83:62)"
          ]
        }
      }
    }
  ],
  "data": {
    "tickets": null
  }
}
``` 
ps "postgres-patch" is postgresJs 2.0.0-beta.3

**Comment by mortifia** [comment]
test 1:
    check1 = 98f2481b-2f6a-51a0-9f75-f58f327a7bb7
test 2:
    check1 = null
    
on two test i have same error

**Comment by mortifia** [comment]
this work (in attempt of patch)

```js
const check1 = (source && source.ticketUuid) || null;
sql`select t.*
      from chat.tickets t
      join chat.ticket_user tu 
        on t.ticket_uuid = tu.ticket_uuid
      where tu.user_uuid = ${this.context.user_uuid}
        and (tu.ticket_uuid = ${check1}
          or ${(source && source.ticketUuid) || 'null'} = 'null')`);
```

**Comment by porsager** [comment]
Ah yes, I was missing a type. Because Postgres.js implicitly creates prepared statements PostgreSQL can't know the type of `null`. You could do like below, but your solution is fine too.

```js
sql`
    select t.*
      from chat.tickets t
      join chat.ticket_user tu 
        on t.ticket_uuid = tu.ticket_uuid
     where tu.user_uuid = ${this.context.user_uuid}
       and (tu.ticket_uuid = ${source.ticketUuid} or ${ source.ticketUuid || null }:uuid is null)`;
```
