### ISSUE TITLE
Prepared statements: "SET TRANSACTION ISOLATION LEVEL must be called before any query"

### ISSUE THREAD

**Issue by dlbeer** [porsager/postgres#164]
Thank you for making this library available -- it's very nicely designed and works well.

I have come across what appears to be a bug specific to prepared statements. I'm using Postgres 9.6.15, Node v14.15.1 and postgres module version c2c0bf18b36640b628dfc0224b1c7d9b86202b9a.

The following test program generates the error in the title of this issue (and I think it shouldn't), but only when prepared statements are enabled:

```javascript
let db = postgres('postgres://', {                                             
    host: '127.0.0.1',
    database: 'dbname',
    username: 'username',                                                        
    password: 'xyzzy',
    max: 1,
// Adding this line fixes the problem
//    no_prepare: true
});     

db.begin(async (db) => {
    await db`SET TRANSACTION ISOLATION LEVEL SERIALIZABLE`; 
    await db`CREATE TEMPORARY TABLE tmp (x INTEGER) ON COMMIT DROP`;
}).then(() => db.begin(async (db) => { 
    await db`SET TRANSACTION ISOLATION LEVEL SERIALIZABLE`; 
    await db`CREATE TEMPORARY TABLE tmp (x INTEGER) ON COMMIT DROP`;
}));
```

The result is:

```
(node:7191) UnhandledPromiseRejectionWarning: PostgresError: SET TRANSACTION ISOLATION LEVEL must be called before any query
    at Object.ErrorResponse (/mnt/work/dlbeer/work/cbridge/cbridge/postgres/backend.js:130:33)
    at Socket.data (/mnt/work/dlbeer/work/cbridge/cbridge/postgres/connection.js:233:25)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at cachedError (/mnt/work/dlbeer/work/cbridge/cbridge/postgres/index.js:195:25)
    at query (/mnt/work/dlbeer/work/cbridge/cbridge/postgres/index.js:169:56)
    at scoped (/mnt/work/dlbeer/work/cbridge/cbridge/postgres/index.js:153:14)
    at /mnt/work/dlbeer/work/cbridge/cbridge/test.js:18:13
```

Logging all statements in Postgres, the server produces the following output:

```
2021-03-25 12:07:44.764 NZDT [7198] dlbeer@cbridge LOG:  execute pfeez1b85oct1: begin
2021-03-25 12:07:44.765 NZDT [7198] dlbeer@cbridge LOG:  execute pfeez1b85oct2: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
2021-03-25 12:07:44.765 NZDT [7198] dlbeer@cbridge LOG:  execute pfeez1b85oct3: CREATE TEMPORARY TABLE tmp_tile (x INTEGER) ON COMMIT DROP
2021-03-25 12:07:44.766 NZDT [7198] dlbeer@cbridge LOG:  execute pfeez1b85oct4: commit
2021-03-25 12:07:44.791 NZDT [7198] dlbeer@cbridge LOG:  execute pfeez1b85oct1: begin
2021-03-25 12:07:44.792 NZDT [7198] dlbeer@cbridge LOG:  execute pfeez1b85oct2: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
2021-03-25 12:07:44.792 NZDT [7198] dlbeer@cbridge ERROR:  SET TRANSACTION ISOLATION LEVEL must be called before any query
2021-03-25 12:07:44.792 NZDT [7198] dlbeer@cbridge STATEMENT:  SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
2021-03-25 12:07:44.794 NZDT [7198] dlbeer@cbridge LOG:  execute pfeez1b85oct5: rollback
```

If I disable prepared statements, the two transactions execute successfully, as I would have expected. Substituting the ``CREATE TEMPORARY TABLE`` statement with an ordinary data manipulation statement (e.g. ``UPDATE ...``) also causes the problem to go away.

**Comment by porsager** [comment]
Have you tried `sql.begin('ISOLATION LEVEL SERIALIZABLE', sql =>...)`?

**Comment by dlbeer** [comment]
That works fine! Would you expect there to be a difference in behaviour between the two?

Postgres log shows:

```
2021-03-25 19:51:21.185 NZDT [19548] dlbeer@cbridge LOG:  execute pg9s33l9lsc1: begin ISOLATION LEVEL SERIALIZABLE
2021-03-25 19:51:21.185 NZDT [19548] dlbeer@cbridge LOG:  execute pg9s33l9lsc2: CREATE TEMPORARY TABLE tmp (x INTEGER) ON COMMIT DROP
2021-03-25 19:51:21.243 NZDT [19548] dlbeer@cbridge LOG:  execute pg9s33l9lsc3: commit
2021-03-25 19:51:21.296 NZDT [19548] dlbeer@cbridge LOG:  execute pg9s33l9lsc1: begin ISOLATION LEVEL SERIALIZABLE
2021-03-25 19:51:21.296 NZDT [19548] dlbeer@cbridge LOG:  execute pg9s33l9lsc2: CREATE TEMPORARY TABLE tmp (x INTEGER) ON COMMIT DROP
2021-03-25 19:51:21.297 NZDT [19548] dlbeer@cbridge LOG:  execute pg9s33l9lsc3: commit
```

**Comment by porsager** [comment]
Hi, sorry for the short answer before, was just on my way out.

I just looked closer at the first log, and that's quite interesting. I'm reproducing it here on PostgreSQL 13 too, and I'm leaning towards this being a bug in PostgreSQL since I can't find anything in their documentation about not allowing the use of `SET TRANSACTION` in a prepared statements.. It's as if it's taking the entire session as the scope.

If `sql.begin('ISOLATION LEVEL SERIALIZABLE', sql => ... )` is working fine for you, I'd recommend using that for now, and if someone has time to investigate further or take it to the PostgreSQL mailing list I'd be curious to learn what's going on. Unfortunately I don't have time to dig deeper myself.

**Comment by alexitheodore** [comment]
I am also experiencing this error. I cannot seem to find any way of putting `SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;` anywhere within the body of the procedure to make postgres happy.

**Comment by porsager** [comment]
Why can't you use sql.begin like mentioned in my previous comment?

**Comment by alexitheodore** [comment]
Ok, you're right - I retract the above.

**Comment by excitoon** [comment]
> Why can't you use sql.begin like mentioned in my previous comment?

@porsager Not all ORMs support it. The error message is misleading, because it is indeed called before any query.
