### ISSUE TITLE
StorePreparedStatement Error connected to PGBouncer

### ISSUE THREAD

**Issue by throrin19** [porsager/postgres#172]
Hello,

I Have a problem with the library only if I try to made my request using pgBouncer connection to final database. If I connect directly to my database, it works fine.

This is the error :  

```
Error: prepared statement \"p1\" already exists
at Object.generic (/opt/nodejs/node_modules/postgres/lib/types.js:200:5)    
at Object.ErrorResponse (/opt/nodejs/node_modules/postgres/lib/backend.js:124:33)\
at Socket.data (/opt/nodejs/node_modules/postgres/lib/connection.js:167:25)
at Socket.emit (events.js:314:20)
at Socket.EventEmitter.emit (domain.js:506:15)
at addChunk (_stream_readable.js:297:12)
at readableAddChunk (_stream_readable.js:272:9)
at Socket.Readable.push (_stream_readable.js:213:10)
at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
at TCP.callbackTrampoline (internal/async_hooks.js:126:14)
```

```
"error": {
    "severity_local": "ERROR",
    "severity": "ERROR",
    "code": "42P05",
    "file": "prepare.c",
    "line": "466",
    "routine": "StorePreparedStatement"
}
```

I try to make my request with pgBouncer connection using another connection than postgres.js (directly with postbird application) and I have no problems.

This is the version of postgres I use : `1.0.2`

**Comment by porsager** [comment]
Hi. 

In v1 prepared statements will collide using pgbouncer due to their naming. This is fixed in v2 by using random names for the prepared statements, but I'm considering backporting the fix to v1.

You can also try postgres@beta (v2) if you like.

**Comment by throrin19** [comment]
It will be great if it's available in v1. I will wait the v2 when it's release in final version (production usage).

Thanks for your response

**Comment by 1N50MN14** [comment]
@porsager Any chance this could be made available in v1?
