### ISSUE TITLE
array of char produce error code 42P18

### ISSUE THREAD

**Issue by mortifia** [porsager/postgres#175]
hello, actually i'm trying to pass an array of string / varchar but i encounter this error

```javascript

      where = {
        string: 'where tu.user_uuid = $1 and title in ($2)',
        data: [ 'abfe29d9-b598-5173-b2ff-0c6a91c88b16',  [ 'coucou', 'ppp' ] ]
      }

      where = { // or this by sql.array(['coucou','ppp'], [25]) || sql.array(['coucou','ppp'])
  string: 'where tu.user_uuid = $1 and title in ($2)',
  data: [ 'abfe29d9-b598-5173-b2ff-0c6a91c88b16', { array: [ 'coucou', 'ppp' ] } ]
}
      // user_uuid = uuid and title = varchar
      unsafe(`
        select t.*
          from chat.tickets t
          join chat.ticket_user tu using(ticket_uuid)
          ${where.string};`, where.data))

```

Expected result :

The array is inserted

Version: 2.0.0-beta.5

**Comment by porsager** [comment]
Did you forget to paste the error? 🙂

**Comment by mortifia** [comment]
```
select t.*
          from chat.tickets t
          join chat.ticket_user tu using(ticket_uuid)
          where tu.user_uuid = $1 and title in ($2); 
          
          [ 'abfe29d9-b598-5173-b2ff-0c6a91c88b16', { array: [ 'coucou', 'ppp' ] } ]
```
```
"extensions": {
        "code": "protectedError",
        "exception": {
          "name": "protectedError",
          "severity_local": "ERREUR",
          "severity": "ERROR",
          "code": "42P18",
          "file": "d:\\pginstaller_13.auto\\postgres.windows-x64\\src\\backend\\tcop\\postgres.c",
          "line": "1499",
          "routine": "exec_parse_message",
          "stacktrace": [
            "PostgresError: n'a pas pu déterminer le type de données du paramètre $3",
            "    at Object.ErrorResponse (C:\\Users\\amela\\OneDrive\\Bureau\\an\\api\\node_modules\\postgres\\lib\\backend.js:130:33)",
            "    at Socket.data (C:\\Users\\amela\\OneDrive\\Bureau\\an\\api\\node_modules\\postgres\\lib\\connection.js:258:25)",
            "    at Socket.emit (events.js:315:20)",
            "    at addChunk (internal/streams/readable.js:309:12)",
            "    at readableAddChunk (internal/streams/readable.js:284:9)",
            "    at Socket.Readable.push (internal/streams/readable.js:223:10)",
            "    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)",
            "    at cachedError (C:\\Users\\amela\\OneDrive\\Bureau\\an\\api\\node_modules\\postgres\\lib\\index.js:195:25)",
            "    at query (C:\\Users\\amela\\OneDrive\\Bureau\\an\\api\\node_modules\\postgres\\lib\\index.js:169:56)",
            "    at Function.unsafe (C:\\Users\\amela\\OneDrive\\Bureau\\an\\api\\node_modules\\postgres\\lib\\index.js:288:14)",
            "    at postgresDB.getTicketsByUserUuid (C:\\Users\\amela\\OneDrive\\Bureau\\an\\api\\postgresDatabase.js:250:65)"
          ]
        }
```

**Comment by porsager** [comment]
Ah i see. You could create an array literal (stringy) and use ANY to check if title is in it.
```js
where = {
  string: 'where tu.user_uuid = $1 and title = ANY($2)',
  data: [ 'abfe29d9-b598-5173-b2ff-0c6a91c88b16',  '{coucou,ppp}' ]
}
```

The reasons your other queries doesn't work is because with unsafe you define the positional variables yourself so passing a js array won't work. Also you can't use `in` with an array, you need to use `= any(array)` instead.

**Comment by mortifia** [comment]
wihout list of args
```js
{
  string: 'where tu.user_uuid = $1',
  data: [ 'abfe29d9-b598-5173-b2ff-0c6a91c88b16' ]
}

{
  "data": {
    "tickets": [
      {
        "title": "kjhkjh"
      },
      {
        "title": "coucou"
      },
      {
        "title": "coucou"
      },
      {
        "title": "bou"
      },
      {
        "title": "ppp"
      },
      {
        "title": "popopo"
      },
      {
        "title": "poipoi"
      },
      {
        "title": "popooo"
      },
      {
        "title": "ffhh"
      },
      {
        "title": "lol"
      },
      {
        "title": "rjgf"
      },
      {
        "title": "popopo"
      },
      {
        "title": "popo"
      },
      {
        "title": "blabla"
      },
      {
        "title": "coucou"
      }
    ]
  }
}
```

with args 
```
{
  string: 'where tu.user_uuid = $1 and title in($2)',
  data: [ 'abfe29d9-b598-5173-b2ff-0c6a91c88b16', '{coucou}' ]
}

{ //or
  string: 'where tu.user_uuid = $1 and title in($2)',
  data: [ 'abfe29d9-b598-5173-b2ff-0c6a91c88b16', "{coucou,ppp}" ]
} 

{
  "data": {
    "tickets": []
  }
}
```

**Comment by porsager** [comment]
You cannot use `in()` like that. You have to use `any` like in my previous comment.

**Comment by mortifia** [comment]
thanks it's work with 
```js
{
  string: 'where tu.user_uuid = $1 and title = any ($2)',
  data: [ 'abfe29d9-b598-5173-b2ff-0c6a91c88b16', '{coucou}' ]
}
```

```sql
select t.*
    from chat.tickets t
    join chat.ticket_user tu using(ticket_uuid)
    where tu.user_uuid = $1 and title = any ($2);
```

**Comment by porsager** [comment]
Great 🙂
