### ISSUE TITLE
how to bulk insert row with jsonb

### ISSUE THREAD

**Issue by alextes** [porsager/postgres#203]
Given a table `peoples` with `name` string, and `meta` jsonb columns.

If I'd like to insert many people, the naive:
```
const peoples = [{name: "alex", meta: {}}];
sql`
	INSERT INTO peoples (name, meta)
	${sql(peoples)}
`;
```

doesn't work, and understandably so, we have to use `sql.json` for the json column but how does one combine this with a bulk insert?

perhaps there is a safe `sql.unsafe` way to do this as a workaround?

**Comment by naumf** [comment]
Does the following approach  `[{name: "alex", meta: JSON.stringify({})}]` work for you?

**Comment by alextes** [comment]
No @naumf , but the error doesn't tell me much.

my code:
```ts
const toBaseFeeInsert = ({
  block,
  baseFees,
}: {
  block: any;
  baseFees: any;
}) => ({
  hash: block.hash,
  number: block.number,
  base_fees: JSON.stringify(baseFees),
  mined_at: `to_timestamp('${getBlockTimestamp(block)}')`,
});

export const storeBaseFeesForBlocks = async (
  analyzedBlocks: { block: any; baseFees: any }[],
): Promise<void> => {
  await sql`
    INSERT INTO base_fees_per_block
      (hash, number, base_fees, mined_at)
    ${sql(analyzedBlocks.map(toBaseFeeInsert))}
  `;
  return undefined;
};

storeBaseFeesForBlocks([
  {
    block: {
      hash: "0x0568d1278245c4b3827f8f582177e2a96ce2440877d65851456f362e4f51dd0f",
      number: 10678809,
      timestamp: 1626853137,
    },
    baseFees: {
      transfers: 1638000,
      contract_use_fees: {
        "0x3a67676a4a263bb905954e480e9f8c308314f900": 9904063,
        "0x58f8b106a3cc9c00330a5560d0abf1f04cb38c76": 523250,
        "0x7a250d5630b4cf539739df2c5dacb4c659f2488d": 1415856,
        "0x0030bacf841fac3681638d6c7cab47504d347bfd": 3584737,
        "0x25b97de40e353369eb8eb0158ce6fc6702e27039": 2431910,
        "0x2f5393bd8f67ba13eb7ed2b2f2638fea64ed4596": 820352,
        "0x2cf3fbad1f2f346f4d0dd3b36fc214bb43e55d63": 658073,
      },
      contract_creation_fees: 0,
    },
  },
]);
```

the error with console.log on the client's debug:
```
$ /Users/alextes/code/gas_analysis/node_modules/.bin/esrun src/base_fees.ts
2
          select b.oid, b.typarray
          from pg_catalog.pg_type a
          left join pg_catalog.pg_type b on b.oid = a.typelem
          where a.typcategory = 'A'
          group by b.oid, b.typarray
          order by b.oid
         []
3 SELECT base_fees
      FROM base_fees_per_block []
/Users/alextes/code/gas_analysis/node_modules/postgres/lib/types.js:69
  return '"' + str.replace(/"/g, '""').replace(/\./g, '"."') + '"'
                   ^

TypeError: str.replace is not a function
    at escape (/Users/alextes/code/gas_analysis/node_modules/postgres/lib/types.js:69:20)
    at /Users/alextes/code/gas_analysis/node_modules/postgres/lib/index.js:503:59
    at Array.reduce (<anonymous>)
    at escapeHelper (/Users/alextes/code/gas_analysis/node_modules/postgres/lib/index.js:503:15)
    at parseHelper (/Users/alextes/code/gas_analysis/node_modules/postgres/lib/index.js:470:12)
    at parseArg (/Users/alextes/code/gas_analysis/node_modules/postgres/lib/index.js:448:11)
    at parse (/Users/alextes/code/gas_analysis/node_modules/postgres/lib/index.js:434:14)
    at send (/Users/alextes/code/gas_analysis/node_modules/postgres/lib/index.js:209:90)
    at /Users/alextes/code/gas_analysis/node_modules/postgres/lib/index.js:181:52
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Minigugus** [comment]
@alextes The dynamic insert generate columns' names. Therefore, `(hash, number, base_fees, mined_at)` disabled dynamic insert and `postgres` considered the value you passed to `sql()` as an array of column names.

I think this fix should work (not tested):
```diff
const toBaseFeeInsert = ({
  block,
  baseFees,
}: {
  block: any;
  baseFees: any;
}) => ({
  hash: block.hash,
  number: block.number,
  base_fees: JSON.stringify(baseFees),
  mined_at: `to_timestamp('${block.timestamp}')`,
});

export const storeBaseFeesForBlocks = async (
  analyzedBlocks: { block: any; baseFees: any }[],
): Promise<void> => {
  await sql`
    INSERT INTO base_fees_per_block
-      (hash, number, base_fees, mined_at)
    ${sql(analyzedBlocks.map(toBaseFeeInsert))}
  `;
  return undefined;
};

storeBaseFeesForBlocks([
  {
    block: {
      hash: "0x0568d1278245c4b3827f8f582177e2a96ce2440877d65851456f362e4f51dd0f",
      number: 10678809,
      timestamp: 1626853137,
    },
    baseFees: {
      transfers: 1638000,
      contract_use_fees: {
        "0x3a67676a4a263bb905954e480e9f8c308314f900": 9904063,
        "0x58f8b106a3cc9c00330a5560d0abf1f04cb38c76": 523250,
        "0x7a250d5630b4cf539739df2c5dacb4c659f2488d": 1415856,
        "0x0030bacf841fac3681638d6c7cab47504d347bfd": 3584737,
        "0x25b97de40e353369eb8eb0158ce6fc6702e27039": 2431910,
        "0x2f5393bd8f67ba13eb7ed2b2f2638fea64ed4596": 820352,
        "0x2cf3fbad1f2f346f4d0dd3b36fc214bb43e55d63": 658073,
      },
      contract_creation_fees: 0,
    },
  },
]);
```

**Comment by naumf** [comment]
@alextes Given the fact you were asking for the jsonb type, I didn't even see that the query is wrong.
@Minigugus is right you should remove the column names from the query, or if you need to specify some of the columns, write them as arguments in the sql function following the array data. See the example here:
https://github.com/porsager/postgres#multiple-inserts-in-one-query

**Comment by metala** [comment]
@alextes you are missing the columns in the sql helper.

This one works for me:
```
// create table tbl ("key" text, "data" jsonb);
const list = [{key: "k", data: JSON.stringify({datum: 0})}];
const result = await sql`
	INSERT INTO tbl
	${sql(list, 'key', 'data')}
`;
```

**Comment by alextes** [comment]
aaah, I see how this works now.

Safe bulk inserts are back in my code. Thank you @naumf @Minigugus and @metala ! 👍 .

**Comment by xerosanyam** [comment]
@naumf what to do if column names are different than key names?
modify them myself before giving to postgres.js or there's some better way to do it?
```
const list = [{usefulKey: "k", usefulData: JSON.stringify({datum: 0})}];
// won't work since columns are key and data
const result = await sql`
	INSERT INTO tbl
	${sql(list, 'usefulKey', 'usefulData')}
```
