### ISSUE TITLE
Node TLS ERR_UNKNOWN_ENCODING: Unknown encoding: 1

### ISSUE THREAD

**Issue by alextes** [porsager/postgres#218]
I haven't yet managed to isolate what piece of code is causing this exactly but downgrading beta-7 to beta-6 solved the issue for me.

Running node 16.

Connecting to a Digital Ocean PG 13, SSL required DB. 

If this is not enough to go off, feel free to ask for details or simply close. The downgrading is no problem for me, but thought you may like to know 👍 .

```
TypeError [ERR_UNKNOWN_ENCODING]: Unknown encoding: 1
    at new NodeError (node:internal/errors:370:5)
    at _write (node:internal/streams/writable:293:13)
    at TLSSocket.Writable.write (node:internal/streams/writable:334:10)
    at write (/Users/alextes/code/gas_analysis/node_modules/postgres/lib/connection.js:433:12)
    at write (/Users/alextes/code/gas_analysis/node_modules/postgres/lib/connection.js:417:16)
    at Array.forEach (<anonymous>)
    at onready (/Users/alextes/code/gas_analysis/node_modules/postgres/lib/connection.js:243:16)
    at Object.ReadyForQuery (/Users/alextes/code/gas_analysis/node_modules/postgres/lib/backend.js:238:5)
    at TLSSocket.data (/Users/alextes/code/gas_analysis/node_modules/postgres/lib/connection.js:297:25)
    at TLSSocket.emit (node:events:394:28)
```

Great lib!

**Comment by porsager** [comment]
Thanks for the report. This should be fixed by https://github.com/porsager/postgres/commit/f40642682853616b091cbc450b32d2a5dbe44e38 and released with beta-8, so would be great if you'd give that a go.

Thanks.

**Comment by alextes** [comment]
fixed 🎉 !

You're a great maintainer 👌 .

this lib is happily powering https://ultrasound.money/ 🥳 .

**Comment by porsager** [comment]
Thanks a lot @alextes , although this prolonged v2 beta period doesn't make me feel like it 😋

That is a really good looking site - congrats! 

I've actually got something really exciting in the works you might find useful too.. I just haven't had the time to write the docs for it. I've just pushed the PR for it -  https://github.com/porsager/postgres/pull/220
