### ISSUE TITLE
sql helper does not work with json props

### ISSUE THREAD

**Issue by TheMaestro1s** [porsager/postgres#242]
```ts
const user = {
  id: '116951063604563968',
  username: 'TheMaestro',
  password: 'good_password',
  email: 'test@email.com',
  presence: { status: 1 },
  relations: [],
  badges: 0,
  avatar: null,
  verified: false
}

await sql`INSERT INTO users ${sql(user)}`
```

Throws the following error:
```bash
PostgresError: syntax error at or near ","
    at Object.ErrorResponse (/home/abdulrahman/Projects/server/node_modules/postgres/lib/backend.js:144:20)
    at Socket.data (/home/abdulrahman/Projects/server/node_modules/postgres/lib/connection.js:319:25)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
    at query (/home/abdulrahman/Projects/server/node_modules/postgres/lib/index.js:187:36)
    at postgres (/home/abdulrahman/Projects/server/node_modules/postgres/lib/index.js:81:12)
    at User.save (/home/abdulrahman/Projects/server/dist/structures/Base.js:33:39)
    at /home/abdulrahman/Projects/server/dist/index.js:59:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  severity_local: 'ERROR',
  severity: 'ERROR',
  code: '42601',
  position: '133',
  file: 'scan.l',
  line: '1176',
  routine: 'scanner_yyerror',
  query: 'INSERT INTO "users" ("id","username","password","email","presence","relations","badges","avatar","verified") values ($1,$2,$3,$4,$5,,$6,$7,$8)',
  parameters: [
    { type: 0, value: '116951063604563968', raw: '116951063604563968' },
    { type: 0, value: 'TheMaestro', raw: 'TheMaestro' },
    { type: 0, value: 'good_password', raw: 'good_password' },
    { type: 0, value: 'test@email.com', raw: 'test@email.com' },
    { type: 0, value: '[object Object]', raw: [Object] },
    { type: 0, value: '0', raw: 0 },
    { type: 0, value: null, raw: null },
    { type: 16, value: 'f', raw: false },
    dynamic: true
  ]
}
```

- Node: `v16.13.0`
- Lib: `2.0.0-beta.11`

**Comment by porsager** [comment]
Yeah, that's right.. you'd need to wrap that in sql.json() or simply stringify it so postgres can cast it for you. Once https://github.com/porsager/postgres/issues/221 is implemented it should work as you expected.

**Comment by TheMaestro1s** [comment]
@porsager Oh Thanks, 
But one question.. why most parameters marked as type `0` - `number`?

**Comment by porsager** [comment]
`0` is the type to use in the PostgreSQL protocol when you want PostgreSQL to infer the type itself.
