### ISSUE TITLE
 TypeError: Cannot read property 'length' of undefined    at Object.DataRow

### ISSUE THREAD

**Issue by Josehower** [porsager/postgres#250]
A weird error happened on our server that seems to reveal a bug in the library.

Is a quite uncommon error that suggests is not an implementation problem but more a library bug.

for some reason under a now unknown circumstance `columns` seems to be undefined here:

https://github.com/porsager/postgres/blob/4a6669c1b623bb89fcf5a9d13dd09aa69c679811/lib/backend.js#L113

I am afraid that the information given may not be sufficient, but it can be an already known issue or something that may add up to another user information.

```sh
   for (let i = 0; i < backend.query.statement.columns.length; i++) {
                                                      ^
TypeError: Cannot read property 'length' of undefined    
at Object.DataRow (/opt/xxx/project/src/node_modules/postgres/lib/backend.js:113:57)    
at Socket.data (/opt/xxx/project/src/node_modules/postgres/lib/connection.js:319:25)    
at Socket.emit (node:events:365:28)    
at addChunk (node:internal/streams/readable:314:12)    
at readableAddChunk (node:internal/streams/readable:289:9)    
at Socket.Readable.push (node:internal/streams/readable:228:10)    
at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
error Command failed with exit code 1.
```

thanks

**Comment by porsager** [comment]
Hi @Josehower .

Yes, that indeed looks like an issue inside Postgres.js. Thanks for reporting. Do you know if this happened during a shutdown of the database?

**Comment by porsager** [comment]
I meant if the database itself was maybe shutting down / restarting / closing the connection to the client at the time. I'll dig in to see if I can find a reason for this error.
