### ISSUE TITLE
unhandledRejection: Promise {   <rejected> TypeError [ERR_MISSING_ARGS]: The "options" or "port" or "path" argument must be specified       at new NodeError (node:internal/errors:329:5)       at Socket.connect (node:net:932:11)       at Object.connect (node:net:197:17)       at Object.connect (C:\GitHub\rcsng\nextjs\node_modules\postgres\lib\connection.js:392:13) {     code: 'ERR_MISSING_ARGS'   } }

### ISSUE THREAD

**Issue by 700software** [porsager/postgres#252]
```js
unhandledRejection: Promise {
  <rejected> TypeError [ERR_MISSING_ARGS]: The "options" or "port" or "path" argument must be specified
      at new NodeError (node:internal/errors:329:5)
      at Socket.connect (node:net:932:11)
      at Object.connect (node:net:197:17)
      at Object.connect (C:\...\node_modules\postgres\lib\connection.js:390:13) {
    code: 'ERR_MISSING_ARGS'
  }
}
```

This error occurs intermittently.

I have an unusual config here: `{ ..., idle_timeout:1, max:5 }`

Error is occuring here: https://github.com/porsager/postgres/blob/4a6669c1b623bb89fcf5a9d13dd09aa69c679811/lib/connection.js#L390

When error occurs it is because `i == 1` but I only have one host and port so `net.connect` is called with options `undefined, undefined` instead of the port number.

I think what is happening is multiple connections are trying to be reopened simultaneously

**Comment by 700software** [comment]
I would move the `i >= options.host.length && (i = 0)` out of the onclose and put it immediately after `net.connect` but that would mess up the failover logic https://github.com/porsager/postgres/blob/master/lib/connection.js#L360

**Comment by 700software** [comment]
Maybe only reopening one at a time would work.. I think multiple are trying to be reopened after all had idle timeout.

**Comment by porsager** [comment]
Thanks a lot for the good description @700software .. I'm currently in the process of a reimplementation of the connection handling since the current implementation doesn't hold up to the requirement of the features it needs to support, as well as more options for dynamic queries, cancellation of queries, max connection lifetime etc. The goal is to resolve issues like these at the same time.

**Comment by porsager** [comment]
Also, just to be sure, this is with beta 11 correct?

**Comment by 700software** [comment]
yes cough cough, that is correct

**Comment by 700software** [comment]
correct, just verified

**Comment by porsager** [comment]
I think I'll remove the failover logic for now since it's buggy and affecting regular usage..

**Comment by 700software** [comment]
beta8 seems to be fine
