### ISSUE TITLE
Placeholder issue with UUID?

### ISSUE THREAD

**Issue by derekmlr** [porsager/postgres#253]
So, I've got a dynamic where clause in the get helper function of a light ORM class I made that gets a record and populates the instance of the class with it. This works fine with string values as far as I know but when I try a UUID type, it keeps giving a syntax error. Unsure if this is my doing or a weird issue with the library and UUIDs (but likely the former).

This is the error:
```
query 
      SELECT *
      FROM users
      WHERE id = $1
      LIMIT 1
params [ '95dc8b4c-5749-40d7-aaa7-f5ca64c4a94a' ]
Error: syntax error at or near "$1"
    at Object.generic (/xxxxxxxxxxxxxx/node_modules/postgres/lib/types.js:200:5)
    at Object.ErrorResponse (/xxxxxxxxxxxxxx/node_modules/postgres/lib/backend.js:124:33)
    at Socket.data (/xxxxxxxxxxxxxx/node_modules/postgres/lib/connection.js:167:25)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  severity_local: 'ERROR',
  severity: 'ERROR',
  code: '42601',
  position: '8',
  file: 'scan.l',
  line: '1180',
  routine: 'scanner_yyerror'
}
```

This is the code, inspired by https://github.com/porsager/postgres/issues/31#issuecomment-584566968
```
  /**
   * Generic record retrieval.
   * @param whereConditionals Object of whereConditionals to search by.
   * Structured as { column: 'value', column2: 'value' } or { 'OR': { column: 'value', column2: 'value' } }
   * @param limit Optional limit of returned records.
   * @param returnColumns Data to return on success.
   */
  async get(
      whereConditionals: {[key: string]:any} = {},
      limit: number|null = null,
      returnColumns: string = '*') {
    const whereParams: any[] = [];
    let whereConjunction = 'AND';

    // Checks if whereConditions specifies a conjunction and uses it.
    if (['and', 'or']
        .some(conjunction => (
            Object.keys(whereConditionals)[0].toLowerCase().includes(conjunction)
          )
        )) {
      whereConjunction = whereConditionals[0].toUpperCase();
      whereConditionals = whereConditionals[0];
    }

    const whereClause = Object.entries(whereConditionals)
        .map(([column, value]) =>
            `${column} = $${whereParams.push(value)}`
        ).join(` ${whereConjunction} `);

    try {
      // TEMP - for testing
      console.log('query', `
      SELECT ${returnColumns}
      FROM ${this.table.name}
      WHERE ${whereClause}
      ${limit ? 'LIMIT ' + limit : ''}`);
      console.log('params', whereParams);
      
      return sql.unsafe(`
          SELECT ${returnColumns}
          FROM ${this.table.name}
          WHERE ${whereClause}
          ${limit ? 'LIMIT ' + limit : ''}`,
        whereParams);
    } catch(error) {
      console.error(error);
    }
  }
  ```
  
Tried a few things, like doing ::uuid and what not, but it just seems to still error out (saying the error is at the ::). Is there something stupidly obvious I'm missing here? This works fine if I pass in a string like { email: 'user@example.com' } but for some reason uuid is giving me issues. And yes, the column is typed for uuid (changing the param value correctly gives a uuid error) so I don't think that's the issue.

Thanks for any help anyone can offer!

**Comment by derekmlr** [comment]
Just a note, running this SQL directly in my postgres db works as intended.
```
SELECT *
FROM users
WHERE id = '95dc8b4c-5749-40d7-aaa7-f5ca64c4a94a'
LIMIT 1
```
So this "should" work.

**Comment by derekmlr** [comment]
Through some more testing, it seemed this is not where the error happened, but with another hidden query. Got confused with where the error got triggered in the chain.

My bad, consider this closed.

**Comment by bas080** [comment]
@derekmlr, I tend to log all queries and values in development to catch incorrect queries sooner and easier.
