### ISSUE TITLE
CREATE TABLE WITH PARAMTERS

### ISSUE THREAD

**Issue by darshanmarathe** [porsager/postgres#260]
Hi 
I am creating dynamic tables on the fly 
```
var createTable = async (tableName) => {
    if(tableName === '') return;
    let _tableName = "MJS_" + tableName.toUpperCase();
   
    console.log(`CREATE TABLE IF NOT EXISTS ${_tableName} (
        ID UUID PRIMARY KEY,
        document JSON
     );`)
    return sql`CREATE TABLE IF NOT EXISTS ${_tableName} (
        ID UUID PRIMARY KEY,
        document JSON
     );`

}
```
When i use query from to console it works in postgres but getting below error while running the code

C:\opensource\min_json_server\node_modules\postgres\lib\types.js:200
    new Error(x.message),
    ^

Error: syntax error at or near "$1"
    at Object.generic (C:\opensource\min_json_server\node_modules\postgres\lib\types.js:200:5)
    at Object.ErrorResponse (C:\opensource\min_json_server\node_modules\postgres\lib\backend.js:124:33)
    at Socket.data (C:\opensource\min_json_server\node_modules\postgres\lib\connection.js:167:25)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
  severity_local: 'ERROR',
  severity: 'ERROR',
  code: '42601',
  position: '28',
  file: 'scan.l',
  line: '1134',
  routine: 'scanner_yyerror'
}

**Comment by darshanmarathe** [comment]
https://github.com/darshanmarathe/min_json_server/blob/postgress/repos/postgres.js

File Name 

https://github.com/darshanmarathe/min_json_server/blob/postgress

**Comment by porsager** [comment]
Table names cannot be defined as raw parameters so you need to use `sql()` to have Postgres.js escape them for you.

This should make it work.

```js
sql`
  CREATE TABLE IF NOT EXISTS ${ sql(_tableName) } (
    ID UUID PRIMARY KEY,
    document JSON
  )
`
```

**Comment by darshanmarathe** [comment]
Thanks worked like chram
