### ISSUE TITLE
[v3] Transactions seem to eat error reasons

### ISSUE THREAD

**Issue by mohe2015** [porsager/postgres#272]
Currently I don't have a minimally reproducible example but I may be able to provide one in a few days if needed (please just tell me then).

```typescript
await sql.begin("READ WRITE", async (tsql) => {
  return await tsql`INSERT INTO sessions (user_id, session_id) VALUES (${dbUser.id}, ${session_id})`;
});
```

throws because the data type of session_id is wrong. Postgresql logs say:
```
Mar 11 16:30:05 arch-luks2 postgres[1459]: 2022-03-11 16:30:05.417 CET [1459] ERROR:  column "session_id" is of type uuid but expression is of type bytea at character 56
Mar 11 16:30:05 arch-luks2 postgres[1459]: 2022-03-11 16:30:05.417 CET [1459] HINT:  You will need to rewrite or cast the expression.
Mar 11 16:30:05 arch-luks2 postgres[1459]: 2022-03-11 16:30:05.417 CET [1459] STATEMENT:  INSERT INTO sessions (user_id, session_id) VALUES ($1, $2)
Mar 11 16:30:05 arch-luks2 postgres[1459]: 2022-03-11 16:30:05.440 CET [1459] ERROR:  current transaction is aborted, commands ignored until end of transaction block
Mar 11 16:30:05 arch-luks2 postgres[1459]: 2022-03-11 16:30:05.440 CET [1459] STATEMENT:  INSERT INTO sessions (user_id, session_id) VALUES ($1, $2)
```
It looks like the command gets repeated although I don't know where in the code this is the case. Is this implemented inside of porsager/postgres?

Nodejs shows:
```
Mar 11 16:30:57 arch-luks2 node[1446]: begin READ WRITE []
Mar 11 16:30:57 arch-luks2 node[1446]: INSERT INTO sessions (user_id, session_id) VALUES ($1, $2) [
Mar 11 16:30:57 arch-luks2 node[1446]:   1,
Mar 11 16:30:57 arch-luks2 node[1446]:   Uint8Array(64) [
Mar 11 16:30:57 arch-luks2 node[1446]:     135,  25,  54, 115,  35,  95,  59, 108, 118,  14, 128,
Mar 11 16:30:57 arch-luks2 node[1446]:      79, 109, 151, 196, 193,  29,  11, 173, 155, 141, 250,
Mar 11 16:30:57 arch-luks2 node[1446]:     175, 187,  96, 128, 104, 102, 210, 137, 164,  90, 114,
Mar 11 16:30:57 arch-luks2 node[1446]:      22,   9,  73,  73, 150,  41, 224,  87, 196, 157,  76,
Mar 11 16:30:57 arch-luks2 node[1446]:     223, 246,  22, 131, 158,  45,  44,  11, 181,  41,  25,
Mar 11 16:30:57 arch-luks2 node[1446]:     149,  71, 234,  92,  58,  94,  83, 116, 103
Mar 11 16:30:57 arch-luks2 node[1446]:   ]
Mar 11 16:30:57 arch-luks2 node[1446]: ]
Mar 11 16:30:57 arch-luks2 node[1446]: INSERT INTO sessions (user_id, session_id) VALUES ($1, $2) [
Mar 11 16:30:57 arch-luks2 node[1446]:   1,
Mar 11 16:30:57 arch-luks2 node[1446]:   Uint8Array(64) [
Mar 11 16:30:57 arch-luks2 node[1446]:     135,  25,  54, 115,  35,  95,  59, 108, 118,  14, 128,
Mar 11 16:30:57 arch-luks2 node[1446]:      79, 109, 151, 196, 193,  29,  11, 173, 155, 141, 250,
Mar 11 16:30:57 arch-luks2 node[1446]:     175, 187,  96, 128, 104, 102, 210, 137, 164,  90, 114,
Mar 11 16:30:57 arch-luks2 node[1446]:      22,   9,  73,  73, 150,  41, 224,  87, 196, 157,  76,
Mar 11 16:30:57 arch-luks2 node[1446]:     223, 246,  22, 131, 158,  45,  44,  11, 181,  41,  25,
Mar 11 16:30:57 arch-luks2 node[1446]:     149,  71, 234,  92,  58,  94,  83, 116, 103
Mar 11 16:30:57 arch-luks2 node[1446]:   ]
Mar 11 16:30:57 arch-luks2 node[1446]: ]
Mar 11 16:30:57 arch-luks2 node[1446]: rollback []
Mar 11 16:30:57 arch-luks2 node[1446]: /opt/projektwahl-lit-production/node_modules/postgres/src/connection.js:751
Mar 11 16:30:57 arch-luks2 node[1446]:     const error = Errors.postgres(parseError(x))
Mar 11 16:30:57 arch-luks2 node[1446]:                          ^
Mar 11 16:30:57 arch-luks2 node[1446]: PostgresError: current transaction is aborted, commands ignored until end of transaction block
Mar 11 16:30:57 arch-luks2 node[1446]:     at null.ErrorResponse (/opt/projektwahl-lit-production/node_modules/postgres/src/connection.js:751:26)
Mar 11 16:30:57 arch-luks2 node[1446]:     at null.handle (/opt/projektwahl-lit-production/node_modules/postgres/src/connection.js:463:7)
Mar 11 16:30:57 arch-luks2 node[1446]:     at Socket.data (/opt/projektwahl-lit-production/node_modules/postgres/src/connection.js:319:9)
Mar 11 16:30:57 arch-luks2 node[1446]:     at Socket.emit (node:events:527:28)
Mar 11 16:30:57 arch-luks2 node[1446]:     at addChunk (node:internal/streams/readable:324:12)
Mar 11 16:30:57 arch-luks2 node[1446]:     at readableAddChunk (node:internal/streams/readable:297:9)
Mar 11 16:30:57 arch-luks2 node[1446]:     at Socket.Readable.push (node:internal/streams/readable:234:10)
Mar 11 16:30:57 arch-luks2 node[1446]:     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
Mar 11 16:30:57 arch-luks2 node[1446]:     this.origin = handler.debug ? new Error().stack : cachedError(this.strings)
Mar 11 16:30:57 arch-luks2 node[1446]:                                   ^
Mar 11 16:30:57 arch-luks2 node[1446]: Error
Mar 11 16:30:57 arch-luks2 node[1446]:     at null.Query (/opt/projektwahl-lit-production/node_modules/postgres/src/query.js:32:35)
Mar 11 16:30:57 arch-luks2 node[1446]:     at null.sql3 (/opt/projektwahl-lit-production/node_modules/postgres/src/index.js:98:11)
Mar 11 16:30:57 arch-luks2 node[1446]:     at null.<anonymous> (/opt/projektwahl-lit-production/src/server/routes/login/index.ts:155:20)
Mar 11 16:30:57 arch-luks2 node[1446]:     at null.result2 (/opt/projektwahl-lit-production/node_modules/postgres/src/index.js:211:21)
Mar 11 16:30:57 arch-luks2 node[1446]:     at new Promise (<anonymous>)
Mar 11 16:30:57 arch-luks2 node[1446]:     at null.scope (/opt/projektwahl-lit-production/node_modules/postgres/src/index.js:209:30)
Mar 11 16:30:57 arch-luks2 node[1446]:     at Function.begin (/opt/projektwahl-lit-production/node_modules/postgres/src/index.js:193:20)
Mar 11 16:30:57 arch-luks2 node[1446]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Mar 11 16:30:57 arch-luks2 node[1446]:     at null.<anonymous> (/opt/projektwahl-lit-production/src/server/routes/login/index.ts:154:5)
Mar 11 16:30:57 arch-luks2 node[1446]:     at null.<anonymous> (/opt/projektwahl-lit-production/src/server/express.ts:125:47) {
Mar 11 16:30:57 arch-luks2 node[1446]:   query: 'INSERT INTO sessions (user_id, session_id) VALUES ($1, $2)',
Mar 11 16:30:57 arch-luks2 node[1446]:   parameters: [
Mar 11 16:30:57 arch-luks2 node[1446]:     1,
Mar 11 16:30:57 arch-luks2 node[1446]:     Uint8Array(64) [
Mar 11 16:30:57 arch-luks2 node[1446]:       135,  25,  54, 115,  35,  95,  59, 108, 118,  14, 128,
Mar 11 16:30:57 arch-luks2 node[1446]:        79, 109, 151, 196, 193,  29,  11, 173, 155, 141, 250,
Mar 11 16:30:57 arch-luks2 node[1446]:       175, 187,  96, 128, 104, 102, 210, 137, 164,  90, 114,
Mar 11 16:30:57 arch-luks2 node[1446]:        22,   9,  73,  73, 150,  41, 224,  87, 196, 157,  76,
Mar 11 16:30:57 arch-luks2 node[1446]:       223, 246,  22, 131, 158,  45,  44,  11, 181,  41,  25,
Mar 11 16:30:57 arch-luks2 node[1446]:       149,  71, 234,  92,  58,  94,  83, 116, 103
Mar 11 16:30:57 arch-luks2 node[1446]:     ]
Mar 11 16:30:57 arch-luks2 node[1446]:   ],
Mar 11 16:30:57 arch-luks2 node[1446]:   args: [
Mar 11 16:30:57 arch-luks2 node[1446]:     1,
Mar 11 16:30:57 arch-luks2 node[1446]:     Uint8Array(64) [
Mar 11 16:30:57 arch-luks2 node[1446]:       135,  25,  54, 115,  35,  95,  59, 108, 118,  14, 128,
Mar 11 16:30:57 arch-luks2 node[1446]:        79, 109, 151, 196, 193,  29,  11, 173, 155, 141, 250,
Mar 11 16:30:57 arch-luks2 node[1446]:       175, 187,  96, 128, 104, 102, 210, 137, 164,  90, 114,
Mar 11 16:30:57 arch-luks2 node[1446]:        22,   9,  73,  73, 150,  41, 224,  87, 196, 157,  76,
Mar 11 16:30:57 arch-luks2 node[1446]:       223, 246,  22, 131, 158,  45,  44,  11, 181,  41,  25,
Mar 11 16:30:57 arch-luks2 node[1446]:       149,  71, 234,  92,  58,  94,  83, 116, 103
Mar 11 16:30:57 arch-luks2 node[1446]:     ]
Mar 11 16:30:57 arch-luks2 node[1446]:   ],
Mar 11 16:30:57 arch-luks2 node[1446]:   types: [ 0, 17 ]
Mar 11 16:30:57 arch-luks2 node[1446]: }
```

The error message is not visible anywhere.

**Comment by porsager** [comment]
I think i should be able to dig into this from what you posted. Not on a computer until Sunday though.

**Comment by porsager** [comment]
Ok, I found the culprit! Postgres.js has functionality to retry queries if a schema change has been made which results in stale prepared statements. If a query error is one of `FetchPreparedStatement | RevalidateCachedQuery | transformAssignedExpr` Postgres.js will remove the prepared statement and rerun the query to see if it works with an updated prepared statement. In your case a `transformAssignedExpr` error is thrown which causes the query to be rerun. 

Now this of course gives the `current transaction is aborted, commands ignored until end of transaction block` instead of the original error, and Postgres.js should handle that properly by returning the initial error instead.

Thanks a lot for the great description, I'm working on a fix right now!

**Comment by porsager** [comment]
Fixed in https://github.com/porsager/postgres/commit/8a1e3ee41cc53699855bd9297541d327ef64c1a7
