### ISSUE TITLE
When fetching types fails an unhandled rejection is triggered:

### ISSUE THREAD

**Issue by porsager** [porsager/postgres#279]
When fetching types fails an unhandled rejection is triggered:
(granted the query was waiting for 120s, error was captured for the outer query, but seems like there is a dangling promise somewhere?)

```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^
PostgresError: query_wait_timeout
    at ErrorResponse (/src/node_modules/.pnpm/github.com+porsager+postgres@3a8efe728057ca4c19437795af79bdbfd60baf4f/node_modules/postgres/cjs/src/connection.js:753:26)
    at handle (/src/node_modules/.pnpm/github.com+porsager+postgres@3a8efe728057ca4c19437795af79bdbfd60baf4f/node_modules/postgres/cjs/src/connection.js:464:6)
    at TLSSocket.data (/src/node_modules/.pnpm/github.com+porsager+postgres@3a8efe728057ca4c19437795af79bdbfd60baf4f/node_modules/postgres/cjs/src/connection.js:319:9)
    at TLSSocket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:199:23)
    at new Query (/src/node_modules/.pnpm/github.com+porsager+postgres@3a8efe728057ca4c19437795af79bdbfd60baf4f/node_modules/postgres/cjs/src/query.js:35:9)
    at fetchArrayTypes (/src/node_modules/.pnpm/github.com+porsager+postgres@3a8efe728057ca4c19437795af79bdbfd60baf4f/node_modules/postgres/cjs/src/connection.js:710:25)
    at ReadyForQuery (/src/node_modules/.pnpm/github.com+porsager+postgres@3a8efe728057ca4c19437795af79bdbfd60baf4f/node_modules/postgres/cjs/src/connection.js:523:16)
    at handle (/src/node_modules/.pnpm/github.com+porsager+postgres@3a8efe728057ca4c19437795af79bdbfd60baf4f/node_modules/postgres/cjs/src/connection.js:464:6)
    at TLSSocket.data (/src/node_modules/.pnpm/github.com+porsager+postgres@3a8efe728057ca4c19437795af79bdbfd60baf4f/node_modules/postgres/cjs/src/connection.js:319:9)
    at TLSSocket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:199:23)
```

edit: might be an issue in my code, will update in case its in the library

_Originally posted by @AVVS in https://github.com/porsager/postgres/issues/259#issuecomment-1071991394_

**Comment by porsager** [comment]
Let me know if you can repro this @AVVS , I can't seem to repro here.

**Comment by porsager** [comment]
Awesome :) Don't hesitate to write here if you run into it again.
