### ISSUE TITLE
where in clause not working for sub select

### ISSUE THREAD

**Issue by RyanDurk** [porsager/postgres#305]
The docs show this working for where in--
```
const users = await sql`
  select
    *
  from users
  where age in ${ sql([68, 75, 23]) }
`
```
Which runs fine, but if you run a subquery with where in you'll have trouble--
```
const a = await sql`insert into users (age)

  select age from users
 where age in ${sql([68, 75, 23])}`
```

The error message is--
`TypeError: str.replace is not a function
    at escape (./node_modules/postgres/cjs/src/types.js:183:20)
    at ./node_modules/postgres/cjs/src/types.js:127:29
    at Array.map (<anonymous>)
    at Object.select [as fn] (./node_modules/postgres/cjs/src/types.js:127:20)
    at Builder.build (./node_modules/postgres/cjs/src/types.js:72:20)
    at stringify (./node_modules/postgres/cjs/src/connection.js:233:42)
    at build (./node_modules/postgres/cjs/src/connection.js:210:20)
    at Object.execute (./node_modules/postgres/cjs/src/connection.js:155:7)
    at go (./node_modules/postgres/cjs/src/index.js:289:14)
    at Promise.handler (./node_modules/postgres/cjs/src/index.js:278:14)
    at cachedError (./node_modules/postgres/cjs/src/query.js:160:23)
    at new Query (./node_modules/postgres/cjs/src/query.js:36:24)
    at sql (./node_modules/postgres/cjs/src/index.js:104:11)`

Same issue with a CTE--
```
  const a = await sql`
with insertables as (
  select age from users
 where age in ${sql([68, 75, 23])}
)

insert into users (age)
select * from insertables
```

sql.unsafe works as a workaround--
```
ages.forEach((age) => {
    if (typeof age !== "number") {
      throw new Error("age is not a number")
    }
  })

const a = await sql`insert into users (age)

  select age from users
 where age in ${sql.unsafe('(' + ages.join('"') + ')')`
```

**Comment by porsager** [comment]
Thanks a lot Ryan, I'll take a closer look tomorrow.

**Comment by porsager** [comment]
Ah, got it - Very nice find. It was an issue with the dynamic helper lookup mistaking the `in` helper for the `insert` helper. I'll push a fix today.
