### ISSUE TITLE
Deno.land Release 3.0.6

### ISSUE THREAD

**Issue by SamStephensTPC** [porsager/postgres#327]
Just making sure I'm not going crazy... but release 3.0.6 on deno.land still has the 

https://deno.land/x/postgresjs@v3.0.6/types/index.d.ts#L436

```
Promise<import('node:stream').Writable>;
Promise<import('node:stream').Readable>;
```
The release notes say this should have been fixed but it still seems to be in the code base which is causing me to get errors.

```
TS2694 [ERROR]: Namespace '__' has no exported member 'Writable'.
    }): Promise<import('node:stream').Writable>;
                                      ~~~~~~~~
    at https://deno.land/x/postgresjs@v3.0.6/types/index.d.ts:436:39

TS2694 [ERROR]: Namespace '__' has no exported member 'Readable'.
    }): Promise<import('node:stream').Readable>;
                                      ~~~~~~~~
    at https://deno.land/x/postgresjs@v3.0.6/types/index.d.ts:441:39

TS2694 [ERROR]: Namespace '__' has no exported member 'Readable'.
    readable(): import('node:stream').Readable;
                                      ~~~~~~~~
    at https://deno.land/x/postgresjs@v3.0.6/types/index.d.ts:521:39

TS2694 [ERROR]: Namespace '__' has no exported member 'Writable'.
    writable(): import('node:stream').Writable;
                                      ~~~~~~~~
    at https://deno.land/x/postgresjs@v3.0.6/types/index.d.ts:522:39
```

**Comment by porsager** [comment]
No you're not going crazy, I found out earlier today there were missing fixes. Would you mind trying the deno-ts-fix branch?

**Comment by SamStephensTPC** [comment]
I'm using it currently and seems to be working great!
