### ISSUE TITLE
Cannot save null values to BigInt columns.

### ISSUE THREAD

**Issue by pbeets** [porsager/postgres#336]
When we pass in `null` to a nullable BigInt column, we get

```
    err: {
      "type": "PostgresError",
      "message": "invalid input syntax for type bigint: \"NaN\"",
      "stack":
          PostgresError: invalid input syntax for type bigint: "NaN"
              at ErrorResponse (/project/node_modules/postgres/cjs/src/connection.js:757:26)
              at handle (/project/node_modules/postgres/cjs/src/connection.js:464:6)
              at Socket.data (/project/node_modules/postgres/cjs/src/connection.js:308:9)
              at Socket.emit (node:events:390:28)
              at addChunk (node:internal/streams/readable:315:12)
              at readableAddChunk (node:internal/streams/readable:289:9)
              at Socket.Readable.push (node:internal/streams/readable:228:10)
              at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
              at cachedError (/project/node_modules/postgres/cjs/src/query.js:166:23)
              at new Query (/project/node_modules/postgres/cjs/src/query.js:36:24)
              at sql (/project/node_modules/postgres/cjs/src/index.js:105:11)
              at Object.update (--redacted--)
      "name": "PostgresError",
      "severity_local": "ERROR",
      "severity": "ERROR",
      "code": "22P02",
      "where": "unnamed portal parameter $5 = '...'",
      "file": "int8.c",
      "line": "124",
      "routine": "scanint8"
    }
```

This looks to be because `BigInt(null)` throws an error `Uncaught TypeError: can't convert null to BigInt`

See (https://github.com/porsager/postgres/commit/36a70df3b872a69b376110f9141feb8a4a080456#diff-f88e99ee55eaab2cb806b05559d83a2ec3ee1539cab8b562245d7046fa6146f9R36)

**Comment by porsager** [comment]
Could you post the code for the query, I can't seem to find any issue - this is what i tested:

```js
const result = await sql`create table test (x bigint)`
await sql`insert into test (x) values (${ null })`
```

**Comment by porsager** [comment]
I think that `"NaN"` might come from somewhere else in your app, but please reopen if you can make a reproducible sample or want to post your query for me to look at.

**Comment by pbeets** [comment]
I think it may have been coming from somewhere else in the app. Will update if I run into it again.
