### ISSUE TITLE
Multiple SELECTS using .map()

### ISSUE THREAD

**Issue by lol2x** [porsager/postgres#356]
Hi, I'm trying to select and concatenate multiple layers of PostGIS ST_AsMVT function - https://postgis.net/docs/ST_AsMVT.html

"Manual" way is working fine:
```javascript  
const mvtTileQuery = async (z, x, y, layers, zoomLevel) => {
    const mvt = await sql`select
(SELECT ST_AsMVT(tile, ${
      layers[0].name
    }) AS tile FROM (SELECT ST_AsMVTGeom(geom, ST_TileEnvelope(${z},${x},${y},ST_MakeEnvelope(141741, 17253,941741, 817253, 2180)), 4096, ${
      layers[0].zoom[zoomLevel].buffer
    }) AS ${sql(layers[0].zoom[zoomLevel].columns)}
                FROM ${sql(layers[0].table)} WHERE ST_Intersects(
                geom,
                ST_TileEnvelope(${z},${x},${y},ST_MakeEnvelope(141741, 17253,941741, 817253, 2180)))
                ) tile)
                ||
                (SELECT ST_AsMVT(tile, ${
                  layers[1].name
                }) AS tile FROM (SELECT ST_AsMVTGeom(geom, ST_TileEnvelope(${z},${x},${y},ST_MakeEnvelope(141741, 17253,941741, 817253, 2180)), 4096, ${
      layers[1].zoom[zoomLevel].buffer
    }) AS ${sql(layers[1].zoom[zoomLevel].columns)}
                FROM ${sql(layers[1].table)} WHERE ST_Intersects(
                geom,
                ST_TileEnvelope(${z},${x},${y},ST_MakeEnvelope(141741, 17253,941741, 817253, 2180)))
                ) tile)
    as mvt`;
    return mvt;
  };
```

however when I'm trying to iterate through array with layers using .map() instead of Buffer i get [object Promise]
code:
```javascript
const mvtTileQuery = async (z, x, y, layers, zoomLevel) => {
    const mvt = await sql`select
        ${layers.map(
          (layer, index) =>
             ${index ? sql`||` : sql``} 
            sql`(SELECT ST_AsMVT(tile, ${
              layer.name
            }) AS tile FROM (SELECT ST_AsMVTGeom(geom, ST_TileEnvelope(${z},${x},${y},ST_MakeEnvelope(141741, 17253,941741, 817253, 2180)), 4096, ${
              layer.zoom[zoomLevel].buffer
            }) AS ${sql(layer.zoom[zoomLevel].columns)}
                FROM ${sql(layer.table)} WHERE ST_Intersects(
                geom,
                ST_TileEnvelope(${z},${x},${y},ST_MakeEnvelope(141741, 17253,941741, 817253, 2180)))
                ) tile)`
        )}
    as mvt`;
    console.log(mvt);
    return mvt;
  };
```

is there my mistake or there is some bug?

**Comment by porsager** [comment]
An array of fragments is not yet in any released version, but you can try to use the current github master repo. Let me know how that works.

**Comment by porsager** [comment]
There also appears to be some syntax error in your examples, could you try to clean them up a bit?

**Comment by porsager** [comment]
I don't know if this is what you want, but it seems to generate a valid query with latest master :) 
```js
const mvtTileQuery = async (z, x, y, layers, zoomLevel) => {
  const mvt = await sql`
    select
    ${
      layers.flatMap((layer, index) => [index ? sql`||` : sql``,
        sql`(
          select st_asmvt(tile, ${ layer.name }) as tile
          from (
            select
              st_asmvtgeom(geom, st_tileenvelope(${z},${x},${y},st_makeenvelope(141741, 17253,941741, 817253, 2180)),
              4096,
              ${ layer.zoom[zoomLevel].buffer }
          ) as ${ sql(layer.zoom[zoomLevel].columns) }
          from ${ sql(layer.table) } where st_intersects(
            geom,
            st_tileenvelope(${z},${x},${y},st_makeenvelope(141741, 17253,941741, 817253, 2180)))
          ) tile
        )`
      ])}
    as mvt
  `
  console.log(mvt)
  return mvt
}

```

**Comment by lol2x** [comment]
Using version:
  └── postgres@3.1.0 (git+ssh://git@github.com/porsager/postgres.git#452a30d8fe6315b9450358eaf8a6572c6ce42b56)
it doesn't work for me, the error is:

```Cannot read properties of undefined (reading 'transform')
    TypeError: Cannot read properties of undefined (reading 'transform')
        at file:///C:/Users/adamk/Documents/vscode/Gminy/webGmina/node_modules/postgres/src/types.js:142:52
        at Array.map (<anonymous>)
        at Object.select [as fn] (file:///C:/Users/adamk/Documents/vscode/Gminy/webGmina/node_modules/postgres/src/types.js:142:18)
        at Builder.build (file:///C:/Users/adamk/Documents/vscode/Gminy/webGmina/node_modules/postgres/src/types.js:72:20)
        at stringify (file:///C:/Users/adamk/Documents/vscode/Gminy/webGmina/node_modules/postgres/src/types.js:105:40)
        at fragment (file:///C:/Users/adamk/Documents/vscode/Gminy/webGmina/node_modules/postgres/src/types.js:116:10)
        at file:///C:/Users/adamk/Documents/vscode/Gminy/webGmina/node_modules/postgres/src/types.js:102:81
        at Array.reduce (<anonymous>)
        at stringify (file:///C:/Users/adamk/Documents/vscode/Gminy/webGmina/node_modules/postgres/src/types.js:102:50)
        at build (file:///C:/Users/adamk/Documents/vscode/Gminy/webGmina/node_modules/postgres/src/connection.js:221:20)
        at new Query (file:///C:/Users/adamk/Documents/vscode/Gminy/webGmina/node_modules/postgres/src/query.js:35:9)
        at sql (file:///C:/Users/adamk/Documents/vscode/Gminy/webGmina/node_modules/postgres/src/index.js:105:11)
        at Object.mvtTileQueryAlternate [as getMvtTile2] (file:///C:/Users/adamk/Documents/vscode/Gminy/webGmina/packages/backend/src/routes/address/tile/mvt.js:63:26)```

**Comment by porsager** [comment]
One of your values is undefined 😉

**Comment by e3dio** [comment]
In his call stack `fragment` function here https://github.com/porsager/postgres/blob/master/src/types.js#L116 is calling `stringify` function with no `options` argument, which gets passed along and ends up throwing error as options = undefined here https://github.com/porsager/postgres/blob/master/src/types.js#L142 so looks like source code issue

**Comment by e3dio** [comment]
Which looks like can be fixed by passing `options` to `fragment` function and calling `stringify` with options

**Comment by porsager** [comment]
@e3dio Ah yes, that is actually correct - Thanks! 

- but it's only shadowing the real error in this example, which is that one or more of his values are undefined.

**Comment by e3dio** [comment]
I see you made update, I was thinking all fragment calls needed to be updated: https://github.com/porsager/postgres/blob/master/src/types.js#L125
https://github.com/porsager/postgres/blob/master/src/types.js#L149

**Comment by porsager** [comment]
on it :) Need to write some tests for these cases too ;)
