### ISSUE TITLE
Error: could not determine data type of parameter $1

### ISSUE THREAD

**Issue by tracker1** [porsager/postgres#36]
Trying to create a user/role dynamically, if I hard code the values, it does work... but parameterized it doesn't...

```js
  console.log(`Check/Create user (${dbInfo.username}:${dbInfo.password})`);
  await sql`
    DO
    $do$
    BEGIN
      IF NOT EXISTS (
          SELECT
          FROM   pg_catalog.pg_roles
          WHERE  rolname = ${dbInfo.username}
      ) THEN
          CREATE ROLE ${sql(dbInfo.username)} LOGIN PASSWORD ${dbInfo.password};
      END IF;
    END
    $do$;
  `;
```

**Comment by joshxyzhimself** [comment]
Also getting this

```
{ username: 'alice', password: 'alice' }
Fri, 28 Feb 2020 00:00:38 GMT Error: could not determine data type of parameter $1
    at Object.generic (/Users/blitz/Documents/project/node_modules/postgres/lib/types.js:200:5)
    at Object.ErrorResponse (/Users/blitz/Documents/project/node_modules/postgres/lib/backend.js:124:33)
    at TLSSocket.data (/Users/blitz/Documents/project/node_modules/postgres/lib/connection.js:167:25)
    at TLSSocket.emit (events.js:305:20)
    at addChunk (_stream_readable.js:341:12)
    at readableAddChunk (_stream_readable.js:316:11)
    at TLSSocket.Readable.push (_stream_readable.js:250:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {
  severity_local: 'ERROR',
  severity: 'ERROR',
  code: '42P18',
  file: 'postgres.c',
  line: '1397',
  routine: 'exec_parse_message'
}
```

```js
    const { username, password } = payload;
    console.log({ username, password });
    const [user] = await sql`
      SELECT *
      FROM users
      WHERE username = '${username}'
      AND password = '${password}';
    `;
```

**Comment by joshxyzhimself** [comment]
Okay that's weird, it worked when I did:

```
    const { username, password } = payload;
    console.log({ username, password });
    const [user] = await sql`
      SELECT *
      FROM users
      WHERE username = ${username}
      AND password = ${password};
    `;
```

**Comment by porsager** [comment]
@joshxyzhimself This is not really related to this issue, but just how the Postgres protocol works and how Postgres.js uses it.

Every value passed is not inserted directly in the query to Postgres, but instead passed as a parameter, and a placeholder (`$1, $2, $3` etc) is inserted in its place. When you place the qoutes around the values like that postgres won't see a parameter placeholder, but simple the string `'$1'`. I hope that makes sense?

**Comment by porsager** [comment]
@tracker1 I don't think you can have PostgreSQL accept parameters inside dollar quoted DO queries, but I'll check up on it and get back to you ;)

**Comment by joshxyzhimself** [comment]
@porsager thanks

What if in this case, where `session.user.projects` is an array of `[1, 2, 3]`

This one works:

```
SELECT
  COUNT(transactions)
  FROM transactions
  WHERE "phaseId" = 1
  AND "projectId" IN (${session.user.projects.join(', ')})
```

But this one doesn't

```
SELECT
  COUNT(transactions)
  FROM transactions
  WHERE "phaseId" = 1
  AND "projectId" IN ${sql.array(session.user.projects)}
```

Showing error of 

```
syntax error at or near "$1"
```

**Comment by porsager** [comment]
Yeah, it makes sense that you can't use parameters like that inside dollar quoted strings as they are just that.. Strings.. Is there a reason you have to use `DO` ?
