### ISSUE TITLE
Get Error Big integer literals are not available in the configured target environment

### ISSUE THREAD

**Issue by Sylor-huang** [porsager/postgres#374]
I use vite to create a project in local

- [x] My package.json like this: 
```json
{
  "name": "bot_test",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "tauri": "tauri"
  },
  "dependencies": {
    "@element-plus/icons-vue": "^1.1.4",
    "@tauri-apps/api": "^1.0.0-rc.5",
    "element-plus": "2.2.0",
    "js-cookie": "^3.0.1",
    "moment-mini": "^2.24.0",
    "path": "^0.12.7",
    "postgres": "^3.2.2",
    "unplugin-auto-import": "^0.7.2",
    "unplugin-vue-components": "^0.19.5",
    "vue": "^3.2.25",
    "vue-router": "^4.0.15",
    "vuex": "^4.0.2",
    "web3": "^1.7.3"
  },
  "devDependencies": {
    "@tauri-apps/cli": "^1.0.0-rc.11",
    "@vitejs/plugin-vue": "^2.3.3",
    "sass": "^1.52.1",
    "unplugin-element-plus": "^0.4.0",
    "vite": "^2.9.9"
  }
}
```

But when I start project, I get the error: `Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")` 

- [x] the error log just like: 

```js
[vite] error while updating dependencies:
Error: Build failed with 2 errors:
node_modules/postgres/src/connection.js:346:91: ERROR: Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
node_modules/postgres/src/connection.js:433:50: ERROR: Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
    at failureErrorWithLog (/Users/mac/MyCodes/swap_bot/node_modules/esbuild/lib/main.js:1603:15)
    at /Users/mac/MyCodes/swap_bot/node_modules/esbuild/lib/main.js:1249:28
    at runOnEndCallbacks (/Users/mac/MyCodes/swap_bot/node_modules/esbuild/lib/main.js:1034:63)
    at buildResponseToResult (/Users/mac/MyCodes/swap_bot/node_modules/esbuild/lib/main.js:1247:7)
    at /Users/mac/MyCodes/swap_bot/node_modules/esbuild/lib/main.js:1356:14
    at /Users/mac/MyCodes/swap_bot/node_modules/esbuild/lib/main.js:666:9
    at handleIncomingPacket (/Users/mac/MyCodes/swap_bot/node_modules/esbuild/lib/main.js:763:9)
    at Socket.readFromStdout (/Users/mac/MyCodes/swap_bot/node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)

```

- [x] I had try to set build target with `es2020`，but it will get another error:  **`ReferenceError: Buffer is not defined`**

https://github.com/sveltejs/kit/issues/859#issuecomment-894556133

Could you please give me some suggestions for modification？ Thanks so much

**Comment by e3dio** [comment]
This library is for Node.js not browsers. You should ask for help in "vite" forum on how to use it, not here

**Comment by Sylor-huang** [comment]
ok

**Comment by PierBover** [comment]
Yeah this is a Vite error. You will need to exclude the dependency from being processed by Vite:

https://vitejs.dev/config/#optimizedeps-exclude
