### ISSUE TITLE
SSL Connection

### ISSUE THREAD

**Issue by emilbayes** [porsager/postgres#38]
Hej Rasmus,

I'm trying to use postgres on Heroku, and they require you connect over SSL. Setting the SSL flag to true did not help much, eg:

```JS
var sql = postgres(process.env.DATABASE_URL, { ssl: true })
```

Gives the following error:

```

Unhandled Rejection at: Promise {
  <rejected> Error: self signed certificate
      at TLSSocket.onConnectSecure (_tls_wrap.js:1473:34)
      at TLSSocket.emit (events.js:311:20)
      at TLSSocket._finishInit (_tls_wrap.js:916:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:686:12) {
    code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
  }
} reason: Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1473:34)
    at TLSSocket.emit (events.js:311:20)
    at TLSSocket._finishInit (_tls_wrap.js:916:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:686:12) {
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
}
```

I wonder whether this is because Heroku selfsigns their postgres ssl certs or if it is a flag that need to be set on the connection?

**Comment by porsager** [comment]
Hey Emil. 

Right, you have to give SSL an object that is passed to node tls, in this case it would be sufficient to have 

```
ssl: {
  rejectUnauthorized: true
}
```

I think this is probably common enough to include in the docs.

**Comment by emilbayes** [comment]
I should just have read the readme more carefully

**Comment by karlhorky** [comment]
Added a PR to document this explicitly in the readme here: https://github.com/porsager/postgres/pull/126
