### ISSUE TITLE
Insert in with not working

### ISSUE THREAD

**Issue by weinr0ck** [porsager/postgres#396]
I have a simple one-to-many relationship between menu and menu_items. The problem I'm running into is that when I create a new menu with items, using the with clause fails.

**Code**
I have the following classes
```
export class MenuItem {
  constructor(
    readonly id: string,
    readonly title: string,
    readonly icon: string,
  ) {}
}

export class Menu {
  constructor(
    readonly id: string,
    readonly projectId: string,
    readonly label: string,
    readonly menuItems: MenuItem[]
  )
}
```

Now, when I try to insert a new menu AND all the items along with it, I get an error. This is my insert function
```
async addMenu(menu: Menu): Promise<boolean> {
  const result = await this.sql`
	WITH added_menu AS (
	  INSERT INTO menu (
		id,
		"projectId",
		label
	  ) VALUES (
		${menu.id},
		${menu.projectId},
		${menu.label}
	  )
	  RETURNING *
	)
	INSERT INTO menu_item ${this.sql(menu.menuItems)}
	RETURNING *`;
  return true;
}
```

This always throws an exception:
```
(node:78780) UnhandledPromiseRejectionWarning: TypeError: str.replace is not a function
    at escape (/Users/erik/rak-core/node_modules/postgres/cjs/src/types.js:210:20)
    at /Users/erik/rak-core/node_modules/postgres/cjs/src/types.js:141:27
    at Array.map (<anonymous>)
    at Object.select [as fn] (/Users/erik/rak-core/node_modules/postgres/cjs/src/types.js:141:18)
    at Builder.build (/Users/erik/rak-core/node_modules/postgres/cjs/src/types.js:72:20)
    at stringify (/Users/erik/rak-core/node_modules/postgres/cjs/src/types.js:104:40)
    at build (/Users/erik/rak-core/node_modules/postgres/cjs/src/connection.js:221:20)
    at Object.execute (/Users/erik/rak-core/node_modules/postgres/cjs/src/connection.js:166:7)
    at go (/Users/erik/rak-core/node_modules/postgres/cjs/src/index.js:294:14)
    at Promise.handler (/Users/erik/rak-core/node_modules/postgres/cjs/src/index.js:283:14)
    at cachedError (/Users/erik/rak-core/node_modules/postgres/cjs/src/query.js:166:23)
    at new Query (/Users/erik/rak-core/node_modules/postgres/cjs/src/query.js:36:24)
    at PostgresProjectMenusRepository.sql (/Users/erik/rak-core/node_modules/postgres/cjs/src/index.js:105:11)
    at PostgresProjectMenusRepository.<anonymous> (/Users/erik/rak-core/dist/apps/server/core/webpack:/rak-core/libs/server/project-management/src/project-menus/adapter/driven/postgres-project-menus.repository.ts:29:34)
```

After a little digging into types.js, it looks like it's traversing the MenuItem as an object, instead of the fields of the object.

**Comment by porsager** [comment]
Well what is menu.menuItems?

**Comment by weinr0ck** [comment]
menu.menuItems is an array of the MenuItem class. You can see this with the Menu class as the last param is `menuItems: MenuItem[]`.
Basically, what I have is a domain model (Menu) that is a little different than the db fields. However, the MenuItem class has the same fields as the db. Hence I have a with clause that manually calls out the parameters for the menu table and another insert into menu_item that relies on the automated finding of applicable fields. So the menu_item insert uses `insert into x ${ sql([...object]) })`. This doesn't appear to be supported.

**Comment by porsager** [comment]
Ah, there was an issue with the dynamic helper identification, so if you update to 3.2.4 you should be good ;)

**Comment by weinr0ck** [comment]
Updated to 3.2.4 and all works as expected. Thanks
