### ISSUE TITLE
Passing value creates syntax error

### ISSUE THREAD

**Issue by JannisKoeksel** [porsager/postgres#488]
Hi I tried to create a new user with: 

**Code**
```js
await sql`CREATE USER ${sql(name)} WITH PASSWORD ${pwd}
```
where name, pwd are strings.

**Error**
```js
node:internal/process/esm_loader:91
    internalBinding('errors').triggerUncaughtException(
                              ^
PostgresError: syntax error at or near "$1"
    at ErrorResponse (file:///D:/Backend2/node_modules/postgres/src/connection.js:761:26)
    at handle (file:///D:/Backend2/node_modules/postgres/src/connection.js:468:6)
    at Socket.data (file:///D:/Backend2/node_modules/postgres/src/connection.js:312:9)
    at Socket.emit (node:events:537:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at new Query (file:///D:/Backend2/node_modules/postgres/src/query.js:35:9)
    at sql (file:///D:/Backend2/node_modules/postgres/src/index.js:105:11)
    at file:///D:/Backend2/tester.js:45:10
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async loadESM (node:internal/process/esm_loader:85:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```
**Logged query**
```js
query: 'CREATE USER "test" WITH PASSWORD $1',
parameters: [ '12345' ],
args: [ Identifier { value: '"test"' }, '12345' ],
types: [ 0 ]
```

**Question**
As far as I have understood one uses 
```js 
${sql(Identifier)}
```
inside  a template to denote Identifiers which results in double quotes.

And one uses just 
```js
${value)
```
to denote values which results in a parameter or the equivalent of single quotes for strings.
How does the proper query look like ?

**Comment by porsager** [comment]
Sorry for the late reply @JannisKoeksel 

This doesn't work because PostgreSQL does not allow a parameter as password. Unfortunately I think the only way would be to use `sql.unsafe` eg. like this 
``` 
await sql`CREATE USER ${ sql(name) } WITH PASSWORD ${ sql.unsafe("'" + pwd + "'") } 
```

Be sure to sanitize the password variable so that it is safe against sql injections then.
