### ISSUE TITLE
Error response during postgres startup not handled properly

### ISSUE THREAD

**Issue by marcbachmann** [porsager/postgres#52]
I detected an issue where the client gets an unexpected response when the postgres server is still starting. This resulted in a crash instead of a rejected query promise.
I switched back to `pg` for now 😅to get everything working.

To reproduce it, just try to do a query against a postgres database that is starting.
E.g. execute `docker restart postgres` and execute some queries while it's starting up.

```
Error: the database system is starting up
    at Object.generic (/app/node_modules/postgres/lib/types.js:200:5)
    at Object.ErrorResponse (/app/node_modules/postgres/lib/backend.js:125:22)
    at Socket.data (/app/node_modules/postgres/lib/connection.js:167:25)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  severity_local: 'FATAL',
  severity: 'FATAL',
  code: '57P03',
  file: 'postmaster.c',
  line: '2265',
  routine: 'ProcessStartupPacket'
}

TypeError: Cannot read property 'result' of undefined
    at Object.RowDescription (/app/node_modules/postgres/lib/backend.js:175:23)
    at Socket.data (/app/node_modules/postgres/lib/connection.js:167:25)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
```

**Comment by porsager** [comment]
Hi @marcbachmann .

Would you mind trying master to see if the error persists?

**Comment by porsager** [comment]
I'm going to close this one out as I'm very sure it's fixed, but do reopen if you can reproduce with `master`
