### ISSUE TITLE
partial query inside COPY query

### ISSUE THREAD

**Issue by skarbovskiy** [porsager/postgres#520]
```
let query = db`SELECT 1`;
const readableStream = await db`
  copy (
    ${query}
  ) to stdout
`.readable();
```
produces 
```
PostgresError: syntax error at end of input
    at ErrorResponse (/node_modules/postgres/cjs/src/connection.js:765:26)
    at handle (/node_modules/postgres/cjs/src/connection.js:468:6)
    at Socket.data (/node_modules/postgres/cjs/src/connection.js:312:9)

```

Looks pretty similar to https://github.com/porsager/postgres/issues/454

**Comment by edongashi** [comment]
Experiencing the same issue:

```js
await sql`COPY ${sql(tableName)} FROM STDIN`.writable()
```

Does not work, and neither does `${sql.unsafe(tableName)}`...

**Comment by porsager** [comment]
Fixed in https://github.com/porsager/postgres/commit/c6bf6be83d10a90c2921b2e476bbf06edc76e99a
