### ISSUE TITLE
Failed to use on FreeBSD

### ISSUE THREAD

**Issue by rj-hwang** [porsager/postgres#586]
```shell
$ uname -a
FreeBSD gf-dev-server 13.1-RELEASE-p3 FreeBSD 13.1-RELEASE-p3 GENERIC amd64

$ deno --version
deno 1.31.1 (release, x86_64-unknown-freebsd)
v8 11.0.226.13
typescript 4.9.4

$ deno task start
Task start deno run --allow-run --allow-read --allow-write --allow-net --allow-env main.ts
error: Uncaught AssertionError: unreachable
  throw new AssertionError("unreachable");
        ^
    at unreachable (https://deno.land/std@0.132.0/testing/asserts.ts:865:9)
    at https://deno.land/std@0.132.0/node/internal_binding/uv.ts:320:7
```

May be try to upgrade to the new deno/std version?

**Comment by porsager** [comment]
Yeah seems like a good idea. That error is not even inside Postgres.js ;)
