### ISSUE TITLE
not auto reconnect when CONNECTION_ENDED

### ISSUE THREAD

**Issue by xxaier** [porsager/postgres#601]
as title
```
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Immediate.<anonymous> (file:///Users/z/art/pkg/bot/adult/node_modules/.pnpm/@w5+pool@0.0.1/node_modules/@w5/pool/index.js:35:13)
write CONNECTION_ENDED 100.68.120.49:9997
UPDATE bot.task SET adult=0 WHERE id=345910
Error: write CONNECTION_ENDED 100.68.120.49:9997
    at Query.handler (file:///Users/z/art/pkg/bot/node_modules/postgres/src/index.js:291:34)
    at Query.handle (file:///Users/z/art/pkg/bot/node_modules/postgres/src/query.js:141:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'CONNECTION_ENDED',
  errno: 'CONNECTION_ENDED',
  address: [ '100.68.120.49' ],
  port: [ 9997 ]
}
345902 https://5ok.pw/h950/S93nUxuFMP4y14jBk6t0Mg /tmp/5ok.pw/S93nUxuFMP4y14jBk6t0Mg.jpg
Trace
    at file:///Users/z/art/pkg/bot/node_modules/@w5/pg/_try.js:101:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///Users/z/art/pkg/bot/adult/lib/hw.js:102:3)
    at async Promise.allSettled (index 1)
    at async isAdult (file:///Users/z/art/pkg/bot/adult/lib/run.js:61:9)
    at async Immediate.<anonymous> (file:///Users/z/art/pkg/bot/adult/node_modules/.pnpm/@w5+pool@0.0.1/node_modules/@w5/pool/index.js:35:13)
write CONNECTION_ENDED 100.68.120.49:9997
INSERT INTO bot.adult_hw (id,terrorism,sexy,porn,politics) VALUES (345902,'{}',100,0,null) ON CONFLICT (id) DO NOTHING
Trace
    at file:///Users/z/art/pkg/bot/node_modules/@w5/pg/_try.js:101:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///Users/z/art/pkg/bot/adult/lib/baidu.js:74:3)
    at async Promise.allSettled (index 0)
    at async isAdult (file:///Users/z/art/pkg/bot/adult/lib/run.js:61:9)
    at async Immediate.<anonymous> (file:///Users/z/art/pkg/bot/adult/node_modules/.pnpm/@w5+pool@0.0.1/node_modules/@w5/pool/index.js:35:13)
write CONNECTION_ENDED 100.68.120.49:9997
INSERT INTO bot.adult_baidu (id,sexy,porn,kind,kind_p) VALUES (345902,1,0,'{7}','{1}') ON CONFLICT(id) DO NOTHING
Trace
    at file:///Users/z/art/pkg/bot/node_modules/@w5/pg/_try.js:101:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Immediate.<anonymous> (file:///Users/z/art/pkg/bot/adult/node_modules/.pnpm/@w5+pool@0.0.1/node_modules/@w5/pool/index.js:35:13)
write CONNECTION_ENDED 100.68.120.49:9997
UPDATE bot.task SET adult=0 WHERE id=345902
Error: write CONNECTION_ENDED 100.68.120.49:9997
    at Query.handler (file:///Users/z/art/pkg/bot/node_modules/postgres/src/index.js:291:34)
    at Query.handle (file:///Users/z/art/pkg/bot/node_modules/postgres/src/query.js:141:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'CONNECTION_ENDED',
  errno: 'CONNECTION_ENDED',
  address: [ '100.68.120.49' ],
  port: [ 9997 ]
}
```

**Comment by xxaier** [comment]
My home and the server are running a program, the database is on the server.
I use https://tailscale.com for networking. The network between my home and the server is not very stable.
Then the network programs can run for a long time, but the programs at home tend to get errors, with the error message above, and don't automatically reconnect once CONNECTION_ENDED appears.
