### ISSUE TITLE
Error: UNDEFINED_VALUE: Undefined values are not allowed

### ISSUE THREAD

**Issue by marwie** [porsager/postgres#630]
Hello,

i have created my sql connection with the following configuration:

```ts
return sqlConnection = postgres({
        host, port, database, username, password,
        transform: (row) => {
            undefined: null // < nullify undefined see https://github.com/porsager/postgres#transform-undefined-values
        },
    });
```

but I occasionally still get the following error:

```ts
[auth][error][AdapterError]: Read more at https://errors.authjs.dev#adaptererror
[auth][cause]: Error: UNDEFINED_VALUE: Undefined values are not allowed
    at handleValue (C:/git/<myProjectPath>/node_modules/postgres/src/types.js:91:42)
    at stringifyValue (C:/git/<myProjectPath>/node_modules/postgres/src/types.js:123:5)
    at Module.stringify (C:/git/<myProjectPath>/node_modules/postgres/src/types.js:109:16)
    at build (C:/git/<myProjectPath>/node_modules/postgres/src/connection.js:234:42)
    at Object.execute (C:/git/<myProjectPath>/node_modules/postgres/src/connection.js:178:7)
    at go (C:/git/<myProjectPath>/node_modules/postgres/src/index.js:301:14)
    at Promise.handler (C:/git/<myProjectPath>/node_modules/postgres/src/index.js:290:14)
    at Promise.handle (C:/git/<myProjectPath>/node_modules/postgres/src/query.js:144:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at cachedError (C:/git/<myProjectPath>/node_modules/postgres/src/query.js:175:23)
    at new Query (C:/git/<myProjectPath>/node_modules/postgres/src/query.js:39:24)
    at sql (C:/git/<myProjectPath>/node_modules/postgres/src/index.js:107:11)
    at linkAccount (C:/git/<myProjectPath>/src/gcloud-postgres-adapter.js:182:37)
```

command:

```ts
const linked = await sql`INSERT INTO
                accounts (userId, type, provider, providerAccountId, refresh_token, access_token, access_token_expires, token_type, scope, id_token, session_state)
                values (${account.userId}, ${account.type}, ${account.provider}, ${account.providerAccountId}, ${account.refresh_token}, ${account.access_token}, ${account.expires_at ?? 0}, ${account.token_type}, ${account.scope}, ${account.id_token}, ${account.session_state})
            `;
```

**Comment by marwie** [comment]
Oh sorry I guess it should be this:

```ts
transform: {
            undefined: null // < nullify undefined see https://github.com/porsager/postgres#transform-undefined-values
        },
```
