### ISSUE TITLE
Max number of parameters (65534) exceeded

### ISSUE THREAD

**Issue by gpmcadam** [porsager/postgres#64]
I've encountered the following error when doing a large `INNER JOIN` when using params:

> "Max number of parameters (65534) exceeded"

The suggestion in the docs is as follows:

> The postgres protocol doesn't allow more than 65534 (16bit) parameters. If you run into this issue there are various workarounds such as using `sql([...])` to escape values instead of passing them as parameters.

However, when I try to do this, my values are being treated as columns by postgres due to the `"` wrapping:

```js
const ids = [ ... ] // huge array
await sql`SELECT * FROM myTable
  INNER JOIN ( VALUES (${sql(ids)}) ) vals(t)
  ON id = t;`;
```

> Error: column "12345" does not exist

How can I use the `sql([...])` function to return a list of values, with single quotes, `'`?

Also, could you please elaborate (perhaps in the docs) as to what the other workarounds might be?

Thanks!

**Comment by Minigugus** [comment]
I don't know if it's possible with PostgreSQL but what about passing directly `ids` as a single parameter and then join over the postgres array ?

**Comment by pauldraper** [comment]
The right way to do variadic things is with arrays.

```ts
SELECT * FROM myTable WHERE id = ANY($1::int[])
```

**Comment by gpmcadam** [comment]
@pauldraper thanks for the reply, that's useful to know.

Do you know of `postgres` provides a way to pass in the array params as per your SQL query?

Thanks!

**Comment by Minigugus** [comment]
@gpmcadam [`sql.array(ids)`](https://github.com/porsager/postgres#arrays-sqlarrayarray) ?

**Comment by porsager** [comment]
@gpmcadam you can do it like @pauldraper mentions by first converting your array in to a stringifyed postgres array and then casting to array in the query:

```js
const ids = [ ... ] // huge array
await sql`
  SELECT * FROM myTable 
  WHERE id = ANY(${ '{' + ids.join(',') + '}' }::int[]);
```

I hope that'll work out for you. I'm a bit hesitant adding things like this to the docs as it's highly dependent on the case how to solve this right and best.

**Comment by joshxyzhimself** [comment]
Encountered this when I was inserting 5000 randomly-generated items with 58 properties each. Had to reduce it to 1000 items.

Large table I know, but still lol.

```js
const created_items = await sql`INSERT INTO ${sql(table.name)} ${sql(items, ...column_names)} RETURNING *`;
```

```sh
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
Error: MAX_PARAMETERS_EXCEEDED: Max number of parameters (65534) exceeded
    at toBuffer (file:///home/user/Documents/project/node_modules/postgres/src/connection.js:180:20)
    at Object.execute (file:///home/user/Documents/project/node_modules/postgres/src/connection.js:167:20)
    at go (file:///home/user/Documents/project/node_modules/postgres/src/index.js:296:14)
    at Query.handler (file:///home/user/Documents/project/node_modules/postgres/src/index.js:285:14)
    at Query.handle (file:///home/user/Documents/project/node_modules/postgres/src/query.js:136:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cachedError (file:///home/user/Documents/project/node_modules/postgres/src/query.js:166:23)
    at new Query (file:///home/user/Documents/project/node_modules/postgres/src/query.js:36:24)
    at sql (file:///home/user/Documents/project/node_modules/postgres/src/index.js:105:11)
    at insert (file:///home/user/Documents/project/node_modules/modules/postgres.mjs:169:34)
```
