### ISSUE TITLE
SyntaxError: The requested module 'postgres' does not provide an export named 'PostgresError'

### ISSUE THREAD

**Issue by oscarhermoso** [porsager/postgres#684]
## Steps to reproduce

* Set up project with following code and dependencies (see collapsed details)
* Run `pnpm run build`

```js
import { PostgresError } from 'postgres';

function tryCreateRow() {
  try {
    /** database call */
  } catch (err) {
    if (
      err instanceof PostgresError &&
      err.code === '23505' &&
      err.constraint_name === 'table_col_key'
    ) return null;
    else throw err;
  }
}
```

## Expected result

Build succeeds

## Actual result

Fine running in dev mode, but fails at build time with error: `SyntaxError: The requested module 'postgres' does not provide an export named 'PostgresError'`

## Workaround

Works fine if I don't unpack `PostgresError` from the import

```diff
-import { PostgresError } from 'postgres';
+import postgres from 'postgres';
```

```diff
-      err instanceof PostgresError && 
+      err instanceof postgres.PostgresError && 
```

## Details

Looks like this might be related to https://github.com/porsager/postgres/issues/226

<details>
  <summary>Dependencies and logs</summary>

#### Versions

```sh
$ pnpm --version
8.3.1
$ node --version
v18.17.0
```

#### `package.json`

```json
{
  "...": "...",
  "type": "module",
  "scripts": {
    "build": "vite build"
  },
  "dependencies": {
      "postgres": "3.3.5",
      "vite": "4.4.9",
      "...": "..."
  }
}
```

### Logs

```
#15 19.37 import { PostgresError } from "postgres";
#15 19.37          ^^^^^^^^^^^^^
#15 19.37 SyntaxError: The requested module 'postgres' does not provide an export named 'PostgresError'
#15 19.37     at ModuleJob._instantiate (node:internal/modules/esm/module_job:131:21)
#15 19.37     at async ModuleJob.run (node:internal/modules/esm/module_job:213:5)
#15 19.37     at async ModuleLoader.import (node:internal/modules/esm/loader:308:24)
#15 19.37     at async analyse (file:///app/node_modules/.pnpm/@sveltejs+kit@1.22.5_svelte@4.1.2_vite@4.4.9/node_modules/@sveltejs/kit/src/core/postbuild/analyse.js:83:16)
#15 19.37     at async MessagePort.<anonymous> (file:///app/node_modules/.pnpm/@sveltejs+kit@1.22.5_svelte@4.1.2_vite@4.4.9/node_modules/@sveltejs/kit/src/utils/fork.js:22:16)
#15 19.37 Emitted 'error' event on Worker instance at:
#15 19.37     at [kOnErrorMessage] (node:internal/worker:326:10)
#15 19.37     at [kOnMessage] (node:internal/worker:337:37)
#15 19.37     at MessagePort.<anonymous> (node:internal/worker:232:57)
#15 19.37     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
#15 19.37     at exports.emitMessage (node:internal/per_context/messageport:23:28)
```

</details>

**Comment by porsager** [comment]
I think this should go in the vite repo then 😉

**Comment by productdevbook** [comment]
There is no `PostgresError` as an export in index.js, I don't think this is related to vite.
