### ISSUE TITLE
WHERE IN throws `TypeError: str.replace is not a function`

### ISSUE THREAD

**Issue by Nepherpitou** [porsager/postgres#701]
Queries with `WHERE IN ${sql()}` fails with error starting from version 3.3.0
```
await sql`
  select
    *
  from users
  where age in ${ sql([68, 75, 23]) }
`
```

Error:
```
TypeError: str.replace is not a function
    at escape (...\node_modules\postgres\cjs\src\types.js:217:20)
    at ...\node_modules\postgres\cjs\src\types.js:213:22
    at Array.map (<anonymous>)
    at escapeIdentifiers (...\node_modules\postgres\cjs\src\types.js:213:13)
    at Object.select [as fn] (...\node_modules\postgres\cjs\src\types.js:139:12)
    at Builder.build (...\node_modules\postgres\cjs\src\types.js:71:17)
    at stringifyValue (...\node_modules\postgres\cjs\src\types.js:109:38)
    at stringify (...\node_modules\postgres\cjs\src\types.js:100:16)
    at build (...\node_modules\postgres\cjs\src\connection.js:223:20)
    at Object.execute (...\node_modules\postgres\cjs\src\connection.js:167:7)
    at go (...\node_modules\postgres\cjs\src\index.js:341:14)
    at Query.handler (...\node_modules\postgres\cjs\src\index.js:330:14)
    at Query.handle (...\node_modules\postgres\cjs\src\query.js:140:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at new Query (...\node_modules\postgres\cjs\src\query.js:35:9)
    at Object.sql (...\node_modules\postgres\cjs\src\index.js:112:11)
```

**Comment by rytido** [comment]
I've only seen this when there's a nested _in_ (which you can get around with a cte). There also seems to be something going on with whether or not there's whitespace after the _in_:

```ts
sql.unsafe(`drop table if exists t; create table t as (select 1 x);`).then(() => {
  // success: not nested
  sql`select x from t where x in ${sql([1])}`
    .then((data) => console.log(data)) // Result [{x: 1}]
    .catch((err) => console.log(err.message));

  // failure: nested without space after outer 'in'
  sql`select x from t where x in(select x from t where x in ${sql([1])})`
    .then((data) => console.log(data))
    .catch((err) => console.log(err.message)); // str.replace is not a function

  // failure: nested without space after inner 'in'
  sql`select x from t where x in (select x from t where x in${sql([1])})`
    .then((data) => console.log(data))
    .catch((err) => console.log(err.message)); // str.replace is not a function

  // success: space after outer and inner 'in'
  sql`select x from t where x in (select x from t where x in ${sql([1])})`
    .then((data) => console.log(data)) // Result [{x: 1}]
    .catch((err) => console.log(err.message));
});
```

**Comment by porsager** [comment]
@Nepherpitou just tried exactly your example and didn't see any issue. Do you have something I can repro?

**Comment by porsager** [comment]
Very nice tests @rytido !! Thank you - I'll look at fixing those and including your tests.

**Comment by alonrbar** [comment]
For what it worth, I had encountered this issue too and the comment by @rytido helped me work around it.
This was my original query:
```javascript
const valuesArray = [
  ["1", "2", "3"]
];

sql`
    DELETE FROM my_table
    WHERE
        col1 = ${val1} AND
        (col2, col3, col4) IN (${sql(valuesArray)})
`;
```
Removing the space directly after the "IN" made it work:
```javascript
sql`
    DELETE FROM my_table
    WHERE
        col1 = ${val1} AND
        (col2, col3, col4) IN(${sql(valuesArray)})
`;
```

**Comment by rozenmd** [comment]
For anyone else coming in from Google, I managed to get this working by replacing:

```
sql`
...
WHERE table.id IN (${sql(valuesArray)});
`
```
with

```
sql`
...
WHERE table.id IN ${sql(valuesArray)};
`
```

Basically, remove the brackets around `${sql(...)}`.

**Comment by micalevisk** [comment]
@Nepherpitou hi! I guess this issue was resolved

**Comment by san7iya** [comment]
Just tested this on postgres@3.4.9 with PostgreSQL 18 — ran the original repro from the issue (select * from users where age in ${sql([68, 75, 23])}) and it returns the correct filtered rows with no error. Might be worth closing unless there's a related edge case still open (saw some nested-IN reports linked in the thread that might be separate).
