### ISSUE TITLE
CONNECT_TIMEOUT with npm module on Deno

### ISSUE THREAD

**Issue by ralfstx** [porsager/postgres#723]
Deno interoperability with npm has come a long way. In a project I work on, `deno.land/x/postgresjs` is actually the last dependency that binds us on `deno`. If we could use the `postgres` npm module instead, this would allow us to use `package.json` instead of `deno.json`, get rid of the buggy Deno tooling for VSCode, and create code that works on both Node *and* Deno.

Unfortunately, when I try to do so with `postgres@3.4.3` I get a connection timeout, while the same code works with the deno port.

```
Error: write CONNECT_TIMEOUT undefined:undefined
    at connectTimedOut (file://my-project/node_modules/.deno/postgres@3.4.3/node_modules/postgres/src/connection.js:257:20)
    at Timeout.done [as _onTimeout] (file://my-project/node_modules/.deno/postgres@3.4.3/node_modules/postgres/src/connection.js:1035:8)
    at cb (ext:deno_node/internal/timers.mjs:63:31)
    at Object.action (ext:deno_web/02_timers.js:151:11)
    at handleTimerMacrotask (ext:deno_web/02_timers.js:65:10)
    at eventLoopTick (ext:core/01_core.js:189:21)
    at cachedError (file://my-project/node_modules/.deno/postgres@3.4.3/node_modules/postgres/src/query.js:170:23)
    at new Query (file://my-project/node_modules/.deno/postgres@3.4.3/node_modules/postgres/src/query.js:36:24)
    at sql (file://my-project/node_modules/.deno/postgres@3.4.3/node_modules/postgres/src/index.js:112:11)
```

Any chance to get this resolved?

**Comment by approached** [comment]
In Bun is a same issue: https://github.com/porsager/postgres/issues/749
How i can it reproduce? Can you create a example?

**Comment by PAdventures** [comment]
I have a similar issue with the following error:
```
Error: write CONNECT_TIMEOUT undefined:undefined
    at connectTimedOut (file:///PATH/TO/DENO/npm/registry.npmjs.org/postgres/3.4.4/src/connection.js:257:20)
    at Timeout.done [as _onTimeout] (file:///PATH/TO/DENO/npm/registry.npmjs.org/postgres/3.4.4/src/connection.js:1033:8)
    at cb (ext:deno_node/internal/timers.mjs:64:31)
    at callback (ext:deno_web/02_timers.js:68:7)
    at eventLoopTick (ext:core/01_core.js:210:13) {
  code: "CONNECT_TIMEOUT",
  errno: "CONNECT_TIMEOUT",
  address: undefined,
  port: undefined
}
```

**Comment by msgerbush** [comment]
I was running into this same issue and it was due to importing 'postgres' from npm.  I switched the import to:
`https://deno.land/x/postgresjs/mod.js` and the timeout went away.  The Deno installation instructions are tucked away here: https://github.com/porsager/postgres/blob/master/deno/README.md

**Comment by riderx** [comment]
Same issue here.  Note to myself do not follow Deno recommendation to use npm prefix ...
https://github.com/supabase/postgres/issues/1447
