### ISSUE TITLE
CONNECTION_CLOSED on subscribe()

### ISSUE THREAD

**Issue by dvv** [porsager/postgres#757]
I use standard
```ts
const { unsubscribe: _unsubscribe } = await sql.subscribe(
  "*",
  (row, info) => {
    console.log("SUB", row, info)
  },
  () => {
    console.log("SUB!")
  },
)
```

and it works well.

When postgres goes down I immediately get
```
Unexpected error during logical streaming - reconnecting Error: write CONNECTION_CLOSED ...
    at closed (https://deno.land/x/postgresjs@v3.4.2/src/connection.js:443:57)
    at https://deno.land/x/postgresjs@v3.4.2/polyfills.js:138:30
    at Array.forEach (<anonymous>)
    at call (https://deno.land/x/postgresjs@v3.4.2/polyfills.js:138:16)
    at closed (https://deno.land/x/postgresjs@v3.4.2/polyfills.js:127:5)
    at success (https://deno.land/x/postgresjs@v3.4.2/polyfills.js:109:7)
    at eventLoopTick (ext:core/01_core.js:189:11) {
  code: "CONNECTION_CLOSED",
  errno: "CONNECTION_CLOSED",
```

When postgres goes up then I get everything working except for the above subscription -- it never reconnects.

**Comment by Louis-Tian** [comment]
Just got caught with the same error. And it's causing my database to bloat with the WAL piling up...

**Comment by Louis-Tian** [comment]
I believe the key problem the "subscribe" creates a *temporary* replication slot on the database. As soon as the database shuts down, that original replication slot is gone forever. Postgres.js at the moment is not smart enough to recreating a new replication slot when the database is back online. 

@porsager What is really problematic at the moment is that there is no way for us to handle it ourselves in this situation. As the error is being completely swallowed by the stream here.
https://github.com/porsager/postgres/blob/6f20a4820c683b33e7670b606d8daf5670f4b973/src/subscribe.js#L99-L107

I think even just rethrow the error would be better. Because then I can catch that error using the global "UncaughtException" event. And even if I don't, the program would completely crash and restarted by the container runtime or process manager alike.

**Comment by dvv** [comment]
@Louis-Tian right.
I also drafted https://github.com/porsager/postgres/compare/master...dvv:postgres:master to move "close" logic uplevel.

**Comment by smartcrash** [comment]
I having this same issue. Have you found a work around for this?

**Comment by X-43A** [comment]
Same issue. A solution would be appreciated. Thanks

**Comment by hanszoons** [comment]
Ran into the same issue. The database connection itself gets reinstated automatically, but the subscription is never recreated without a full client restart.

**Comment by pmielle** [comment]
hey, same issue here. Any solutions/workarounds? Thanks!

**Comment by IAkumaI** [comment]
Any progress on this?
