### ISSUE TITLE
Dynamic column selection with nested tagged string error

### ISSUE THREAD

**Issue by lolgesten** [porsager/postgres#777]
In issue https://github.com/porsager/postgres/issues/588 it says mixing string and tagged string as dynamic columns should work:

```js
const columns = ['name', 'ST_AsText(location) as loc_txt'];
const cities = await sql`SELECT ${sql.unsafe(columns.join(','))} FROM city`;
```

However trying this locally, I get an error. As far as I can tell the function `escape`, `str.replace` expects only strings, where the tagged string is a `Promise`. 

Is this a regression or intentional?

```
$ node
Welcome to Node.js v21.2.0.
Type ".help" for more information.
> const sql = require('postgres')();
undefined
> const columns = ['name', sql`ST_AsText(location) as loc_txt`];
undefined
> const cities = await sql`SELECT ${sql(columns)} FROM city`;
Uncaught TypeError: str.replace is not a function
    at escape (/Users/martin/dev/lk/ultron/node_modules/postgres/cjs/src/types.js:217:20)
    at /Users/martin/dev/lk/ultron/node_modules/postgres/cjs/src/types.js:213:22
    at Array.map (<anonymous>)
    at escapeIdentifiers (/Users/martin/dev/lk/ultron/node_modules/postgres/cjs/src/types.js:213:13)
    at Object.select [as fn] (/Users/martin/dev/lk/ultron/node_modules/postgres/cjs/src/types.js:139:12)
    at Builder.build (/Users/martin/dev/lk/ultron/node_modules/postgres/cjs/src/types.js:71:17)
    at stringifyValue (/Users/martin/dev/lk/ultron/node_modules/postgres/cjs/src/types.js:109:38)
    at stringify (/Users/martin/dev/lk/ultron/node_modules/postgres/cjs/src/types.js:100:16)
    at build (/Users/martin/dev/lk/ultron/node_modules/postgres/cjs/src/connection.js:223:20)
    at execute (/Users/martin/dev/lk/ultron/node_modules/postgres/cjs/src/connection.js:167:7)
    at cachedError (/Users/martin/dev/lk/ultron/node_modules/postgres/cjs/src/query.js:170:23)
    at new Query (/Users/martin/dev/lk/ultron/node_modules/postgres/cjs/src/query.js:36:24)
    at sql (/Users/martin/dev/lk/ultron/node_modules/postgres/cjs/src/index.js:112:11)
    at REPL3:1:52
    at cachedError (/Users/martin/dev/lk/ultron/node_modules/postgres/cjs/src/query.js:170:23)
    at new Query (/Users/martin/dev/lk/ultron/node_modules/postgres/cjs/src/query.js:36:24)
    at sql (/Users/martin/dev/lk/ultron/node_modules/postgres/cjs/src/index.js:112:11)
    at REPL3:1:52
```

**Comment by alonrbar** [comment]
Seems like the same issue as #701. There's a workaround there you might find useful.
