### ISSUE TITLE
Never-ending CONNECTION_CLOSED errors

### ISSUE THREAD

**Issue by TimChinye** [porsager/postgres#921]
I'm putting this here since [the docs state](<https://www.npmjs.com/package/postgres/v/1.0.0#connection_closed>): This should not happen during normal operation, so please create an issue if this was unexpected.

So, my node projects makes about one database query call every 10 minutes, and every now and then, I get errors like these:
![image](https://github.com/user-attachments/assets/19a34cfd-85f4-497c-910f-49dc9aa120bd)

The error in text-form:
```
Error during getGlobalLeaderboards: Error: write CONNECTION_CLOSED ep-wandering-snowflake-a2isl6k2-pooler.eu-central-1.aws.neon.tech:5432
    at TLSSocket.closed (/home/container/node_modules/postgres/cjs/src/connection.js:438:57)
    at TLSSocket.emit (node:events:529:35)
    at node:net:350:12
    at Socket.done (node:_tls_wrap:657:7)
    at Object.onceWrapper (node:events:632:26)
    at Socket.emit (node:events:517:28)
    at TCP.<anonymous> (node:net:350:12)
    at cachedError (/home/container/node_modules/postgres/cjs/src/query.js:170:23)
    at new Query (/home/container/node_modules/postgres/cjs/src/query.js:36:24)
    at sql (/home/container/node_modules/postgres/cjs/src/index.js:112:11)
    at getGlobalLeaderboards (/home/container/Discord Bots/resources/databases/Bomber Bot XP - DB.js:119:41) {
  code: 'CONNECTION_CLOSED',
  errno: 'CONNECTION_CLOSED',
  address: [
    'ep-wandering-snowflake-a2isl6k2-pooler.eu-central-1.aws.neon.tech'
  ],
  port: [ 5432 ]
}
```

The connection to my database is closing, how do I solve that from happening? Or is it possible to programmatically check if my connection is closed, and if so, re-open it, and run the query again?

Here's what my code looks like:
```js
const postgres = require("postgres");

let { PGHOST, PGDATABASE, PGUSER, PGPASSWORD, ENDPOINT_ID } = process.env;

const sql = postgres({
    host: PGHOST,
    database: PGDATABASE,
    username: PGUSER,
    password: PGPASSWORD,
    port: 5432,
    ssl: "require",
    connection: {
        options: `project=${ENDPOINT_ID}`,
    },
    onnotice: false
});

const getBomber = async (id) => {
    try {
        if (!id) {
            console.log("Error during getBomber: No ID provided.");
            return;
        }
        return (await sql`SELECT * FROM bomber WHERE id = ${id}`)[0];
    } catch (error) {
        console.error('Error during getBomber:', error);
        return 'error';
    }
};
```Also, I'm using a "pooler", could be apart of the issue -I don't really know the difference between a pool and client, iirc the pool is for many queries in one session or something? And since my bot is 24/7 it seemed appropiate, but I'm not fully sure.

**Comment by amjed-ali-k** [comment]
Are you using bun?
