### ISSUE TITLE
number are escaped as if they wehere string 

### ISSUE THREAD

**Issue by ecochard** [porsager/postgres#947]
Hi

version 3.4.4 / in typescript

when using this simple expression (array of numeric values):

```
sql`select * from system.groups where id in ( ${sql([1,2,5])} )`
```

I get this error:

```
Uncaught TypeError TypeError: str.replace is not a function
    at escape (xxx\node_modules\postgres\src\types.js:217:20)
    at <anonymous> (xxx\node_modules\postgres\src\types.js:213:22)
    at escapeIdentifiers (xxx\node_modules\postgres\src\types.js:213:13)
    at select (xxx\node_modules\postgres\src\types.js:139:12)
    at build (xxx\node_modules\postgres\src\types.js:71:17)
    at stringifyValue (xxx\node_modules\postgres\src\types.js:109:38)
    at stringify (xxx\node_modules\postgres\src\types.js:100:16)
    at build (xxx\node_modules\postgres\src\connection.js:223:20)
    at execute (xxx\node_modules\postgres\src\connection.js:167:7)
    at go (xxx\node_modules\postgres\src\index.js:344:14)
    at handler (xxx\node_modules\postgres\src\index.js:333:14)
    at handle (xxx\node_modules\postgres\src\query.js:140:65)
    at processTicksAndRejections (internal/process/task_queues:95:5)
```

code involved:
str is not a string but a number

```
export const escapeIdentifier = function escape(str) {
  return '"' + str.replace(/"/g, '""').replace(/\./g, '"."') + '"'
}
```

do I miss something ?

Regards

**Comment by boromisp** [comment]
Based on the example in the readme you don't need parentheses around the parameter for `WHERE ... IN` queries:
https://github.com/porsager/postgres?tab=readme-ov-file#dynamic-values-and-where-in

**Comment by ecochard** [comment]
OK, nice point
thanks
